### PR TITLE
SSH: Add persistent TMUX settings.

### PR DESCRIPTION
**Pull request by rigoorozco**
Updated profile.sh to copy the default .tmux.conf to the /data directory and then create a symbolic link to it at /root. This allows changes to TMUX bindings and other settings to be persistent across reboots.

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @rigoorozco, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;addons#1689).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by rigoorozco** [comment]
@ludeeus Anything else needed to get this merged?

**Comment by ludeeus** [comment]
@rigoorozco Can you update the changelog and version as @pvizeli mentioned?

**Comment by ludeeus** [comment]
replaced by #2191

**Pull request closed without merging**
