### PR TITLE
silabs-multiprotocol: Update REST API patches for OTBR

### PR DESCRIPTION
**Pull request by agners**

### CODE REVIEW

**Comment by MattWestb** [comment]
Sup is complaining of `22-12-28 17:21:43 WARNING (MainThread) [supervisor.addons.options] Option 'otbr_debug' does not exist in the schema for Silicon Labs Multiprotocol (core_silabs_multiprotocol)` but i think its only cosmetic.

**Comment by MattWestb** [comment]
Matter server is complaining :-(((
`Config entry 'ws://core-matter-server:5580/ws' for matter integration not ready yet: Invalid server version: Matter Server SDK version is incompatible: 2022.12.0 version on the client is 2022.11.1 ; Retrying in background`

**Comment by agners** [comment]
> Matter server is complaining :-((( `Config entry 'ws://core-matter-server:5580/ws' for matter integration not ready yet: Invalid server version: Matter Server SDK version is incompatible: 2022.12.0 version on the client is 2022.11.1 ; Retrying in background`

That is not related to this add-on.

**Comment by agners** [comment]
> Sup is complaining of `22-12-28 17:21:43 WARNING (MainThread) [supervisor.addons.options] Option 'otbr_debug' does not exist in the schema for Silicon Labs Multiprotocol (core_silabs_multiprotocol)` but i think its only cosmetic.

You probably can fix this by uninstalling and reinstalling the add-on.

**Comment by MattWestb** [comment]
Deleted and reinstalled addon was fixing the warning in Supp log and must rejoining the network.
Patching HA manifest `python matter server` to `1.0.8` and its not making trouble.

Thanks for helping !!

**Pull request merged**
