### PR TITLE
Upgrade certbot; add preferred chain flag

### PR DESCRIPTION
**Pull request by nkm8**
Context: Running the Adguard Home add-on with DNS-over-TLS enabled, I noticed that DoT on my Android phone stopped working earlier today. After some research, the issue is a a side-effect from the root cert expiration earlier today: https://scotthelme.co.uk/lets-encrypt-old-root-expiration/

The required flag `--preferred-chain <issuer CN>` was added in certbot 1.6.0: https://github.com/certbot/certbot/releases/tag/v1.6.0

Related discussions (with solutions provided):
- https://community.letsencrypt.org/t/android-devices-with-dot-configured-interaction-with-new-default-chain/161020/14
- https://github.com/AdguardTeam/AdGuardHome/issues/3689#issuecomment-931643378

### CODE REVIEW

**Comment by SamJongenelen** [comment]
Any news on this?

**Comment by nkm8** [comment]
I just rebased the changes with the latest from master - someone else updated certbot: https://github.com/home-assistant/addons/blob/master/letsencrypt/build.yaml#L16

The remaining changes in this PR are still needed.

**Comment by SamJongenelen** [comment]
@pvizeli could you please review this PR? Thank you very much in advance.

**Comment by SamJongenelen** [comment]
So, I couldnt wait anymore and installed this branch version manually. Works perfectly

**Comment by vins345** [comment]
when this PR will be added?

**Comment by rubenverhoef** [comment]
Any update on this PR? I would like to use doh on my Android device.

**Review by mdegat01 — APPROVED** [review]

**Comment by mdegat01** [comment]
The only thing not clear to me was why everyone would want to use this chain from here on out instead of making it a new option. But I found [this](https://letsencrypt.org/2019/04/15/transitioning-to-isrg-root.html), looks like the recommendation is coming from Let's Encrypt themselves so this makes sense.

Thanks @nkm8 👍

**Comment by mdegat01** [comment]
Wait @nkm8 you never updated the changelog and version. Crap, I'll fix it

**Comment by nkm8** [comment]
> Wait @nkm8 you never updated the changelog and version. Crap, I'll fix it

Sorry, first time contribution - I'll remember for next time :+1:

**Pull request merged**
