### PR TITLE
SSH: Add git-perl to have git-add--interactive available

### PR DESCRIPTION
**Pull request by lazyfrosch**
I tend to use `git add -p` and this is only included in git-perl

Also see https://pkgs.alpinelinux.org/contents?branch=edge&name=git-perl&arch=armhf&repo=main

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @lazyfrosch, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;hassio-addons#1628).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by pvizeli** [comment]
what are the size differences of the image with this?

**Comment by lazyfrosch** [comment]
@pvizeli Since CI doesn't actually build the image on PR, I did it manually:

```
homeassistant/armhf-addon-ssh                                 with-git-interactive   a72ce074e858        2 seconds ago       176MB
homeassistant/armhf-addon-ssh                                 latest                 a4ad1d1af135        4 weeks ago         148MB
```

So about 28 MB.

**Comment by lazyfrosch** [comment]
Alternatively we could introduce some configuration to run custom commands on startup of the container.

**Comment by ludeeus** [comment]
> pvizeli Since CI doesn't actually build the image on PR, I did it manually:

If you rebase now @lazyfrosch it actually does ;)

**Comment by lazyfrosch** [comment]
At least its green! :D

**Comment by ludeeus** [comment]
If you scroll to the bottom of the build logs, it also does a `docker images` so we get the size as well

**Comment by lazyfrosch** [comment]
Merge or not? :wink: 

Could we at least add some installation hooks to the config, so you can install or do certain things on starting the addon?

**Comment by pvizeli** [comment]
Make an option to install packages on start, so we cover multiple use case

**Pull request closed without merging**
