### PR TITLE
letsencrypt: Added support for GoDaddy DNS challenge

### PR DESCRIPTION
**Pull request by dim-0**
* Update build.yaml

* Update run

* Update file-structure.sh

* Update config.yaml

* Update Dockerfile

* Update CHANGELOG.md

* Update build.yaml

* Version bump

* Update DOCS.md

## Summary by CodeRabbit

- **New Features**
	- Introduced support for GoDaddy DNS, allowing users to manage DNS challenges for domains registered with GoDaddy.
	- Added new configuration parameters for GoDaddy in the management tool, including `godaddy_secret` and `godaddy_key`.

- **Documentation**
	- Updated documentation to include GoDaddy as a supported DNS provider, with specific configuration examples.

- **Bug Fixes**
	- Minor version update from 5.1.2 to 5.1.3 reflecting the new DNS provider capabilities.

### CODE REVIEW

**Review by agners — COMMENTED** [review]
Generally LGTM. With #3733 merged, this needs a rebase and adjusted changelog/config.yaml version entries.

**Comment by agners** [comment]
> The added change looks fine, however, we're getting into the dependency hell 😢

Hm, yeah it seems GoDaddy requires Certbot 2.8.0:

https://github.com/miigotu/certbot-dns-godaddy/blob/324f57ed4423e10a1761ba5be409d1dbe0d6d25c/pyproject.toml#L32

Probably best if we bump Certbot first in a separate PR :thinking:

**Comment by sairon** [comment]
I'm afraid that won't do it, because `certbot-dns-godaddy 2.8.0 depends on certbot>=2.8.0`. The collision comes from `certbot-dns-cloudns 0.6.0 depends on certbot<2.8.0 and >=2.7.4`

**Comment by sairon** [comment]
> It's been a while we bumped Certbot itself. Probably best if we bump Certbot first in a separate PR 🤔

That would need a change in a third-party dependency, because the collision comes from another package:
```
certbot-dns-cloudns 0.6.0 depends on certbot<2.8.0 and >=2.7.4
```

**Comment by sairon** [comment]
@dim-0 The requirements should be fine now, could you please also remove the TTL option from other places?

**Review by sairon — APPROVED** [review]
LGTM, thanks!

**Review by sairon — APPROVED** [review]

**Review by agners — APPROVED** [review]
LGTM, thanks!

**Review by agners — APPROVED** [review]

**Pull request merged**
