### PR TITLE
Bump zwave-js-server to 1.3.0

### PR DESCRIPTION
**Pull request by raman325**
Changelog: https://github.com/zwave-js/zwave-js-server/releases/tag/1.3.0

### CODE REVIEW

**Review by frenck — APPROVED** [review]
LGTM ✅ 

Not sure if we can merge e.g., compatibility and such?

**Comment by raman325** [comment]
It's intended to be backwards compatible so it should be ok to release

**Review by balloob — APPROVED** [review]

**Comment by balloob** [comment]
The goal of ZJS Server is to be the place where we solve compatibility issues and so support older versions of HA and newer ones (cur version HA uses schema 2, this server also supports schema 3). So this is ok to go. Leaving it up to @MartinHjelmare for final sign off because I don't know if it is tested, just know the theory.

**Comment by raman325** [comment]
FWIW I am running the master branch of `zwave-js-server` in my production HA instance (2021.3), everything appears to be working as expected

**Comment by MartinHjelmare** [comment]
I'll test a bit tomorrow too and then merge if everything is alright.

**Review by MartinHjelmare — APPROVED** [review]
Local build and test works well.

**Pull request merged**
