### PR TITLE
letsencrypt: Add support for dreamhost

### PR DESCRIPTION
**Pull request by glogiotatidis**
Adds support for Dreamhost DNS provider for Let's Encrypt certificates.

### CODE REVIEW

**Comment by agners** [comment]
@glogiotatidis the add-on now got updated to the latest Alpine version etc. Can you resolve the merge conflict? Then we should be able to merge this soon.

**Comment by glogiotatidis** [comment]
@agners rebased!

**Comment by agners** [comment]
@glogiotatidis can you also update CHANGELOG.md and bump the version in config.yaml (like #3353).

**Comment by glogiotatidis** [comment]
@agners done

**Review by agners — APPROVED** [review]

**Pull request merged**
