### PR TITLE
Bump Matter server to 3.2.0

### PR DESCRIPTION
**Pull request by mrflo97**

### CODE REVIEW

**Comment by MartinHjelmare** [comment]
Have you tested building and running the add-on with this server version?

**Comment by mrflo97** [comment]
Funny enough, I can build it on my secondary PI, but not on my HASSIO PI.
I copied the whole directory into /addons/matter-server, and commented out the „image: […]“ line in the config.yml to get it to build locally.
Now when trying to add the add-on, it is failing with this error message in the supervisor log:

`Can't build local/aarch64-addon-matter_server:4.2.0: The command '/bin/bash -o pipefail -c set -x     && apt-get update && apt-get install -y --no-install-recommends         bash         jq         tzdata         curl         ca-certificates         xz-utils     && mkdir -p /usr/share/man/man1         && if [ "${BUILD_ARCH}" = "armv7" ]; then             export S6_ARCH="arm";         elif [ "${BUILD_ARCH}" = "i386" ]; then             export S6_ARCH="i686";         elif [ "${BUILD_ARCH}" = "amd64" ]; then             export S6_ARCH="x86_64";         else             export S6_ARCH="${BUILD_ARCH}";         fi         && curl -L -f -s "https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-${S6_ARCH}.tar.xz"         | tar Jxvf - -C /     && curl -L -f -s "https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-noarch.tar.xz"         | tar Jxvf - -C /     && curl -L -f -s "https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-symlinks-arch.tar.xz"         | tar Jxvf - -C /     && curl -L -f -s "https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-symlinks-noarch.tar.xz"         | tar Jxvf - -C /     && mkdir -p /etc/fix-attrs.d     && mkdir -p /etc/services.d         && curl -L -f -s -o /usr/bin/tempio         "https://github.com/home-assistant/tempio/releases/download/${TEMPIO_VERSION}/tempio_${BUILD_ARCH}"     && chmod a+x /usr/bin/tempio         && mkdir -p /usr/src/bashio     && curl -L -f -s "https://github.com/hassio-addons/bashio/archive/v${BASHIO_VERSION}.tar.gz"         | tar -xzf - --strip 1 -C /usr/src/bashio     && mv /usr/src/bashio/lib /usr/lib/bashio     && ln -s /usr/lib/bashio/bashio /usr/bin/bashio         && rm -rf /var/lib/apt/lists/*     && rm -rf /usr/src/*' returned a non-zero code: 127
23-03-30 14:56:25 ERROR (SyncWorker_1) [supervisor.docker.addon] Build log: 
Step 1/21 : ARG BUILD_FROM
Step 2/21 : FROM ${BUILD_FROM}
 ---> 84115889a148
Step 3/21 : ENV     LANG="C.UTF-8"     DEBIAN_FRONTEND="noninteractive"     CURL_CA_BUNDLE="/etc/ssl/certs/ca-certificates.crt"     S6_BEHAVIOUR_IF_STAGE2_FAILS=2     S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0     S6_CMD_WAIT_FOR_SERVICES=1     S6_SERVICES_READYTIME=50
 ---> Using cache
 ---> 45f9f96c2c09
Step 4/21 : SHELL ["/bin/bash", "-o", "pipefail", "-c"]
 ---> Using cache
 ---> 5c01f1d7aac6
Step 5/21 : ARG     BASHIO_VERSION     TEMPIO_VERSION     S6_OVERLAY_VERSION     QEMU_CPU
 ---> Using cache
 ---> 8d6a14ec9c47
Step 6/21 : WORKDIR /usr/src
 ---> Using cache
 ---> d5d342ce8b4e
Step 7/21 : ARG BUILD_ARCH
 ---> Using cache
 ---> 7c8987702210
Step 8/21 : RUN     set -x     && apt-get update && apt-get install -y --no-install-recommends         bash         jq         tzdata         curl         ca-certificates         xz-utils     && mkdir -p /usr/share/man/man1         && if [ "${BUILD_ARCH}" = "armv7" ]; then             export S6_ARCH="arm";         elif [ "${BUILD_ARCH}" = "i386" ]; then             export S6_ARCH="i686";         elif [ "${BUILD_ARCH}" = "amd64" ]; then             export S6_ARCH="x86_64";         else             export S6_ARCH="${BUILD_ARCH}";         fi         && curl -L -f -s "https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-${S6_ARCH}.tar.xz"         | tar Jxvf - -C /     && curl -L -f -s "https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-noarch.tar.xz"         | tar Jxvf - -C /     && curl -L -f -s "https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-symlinks-arch.tar.xz"         | tar Jxvf - -C /     && curl -L -f -s "https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-symlinks-noarch.tar.xz"         | tar Jxvf - -C /     && mkdir -p /etc/fix-attrs.d     && mkdir -p /etc/services.d         && curl -L -f -s -o /usr/bin/tempio         "https://github.com/home-assistant/tempio/releases/download/${TEMPIO_VERSION}/tempio_${BUILD_ARCH}"     && chmod a+x /usr/bin/tempio         && mkdir -p /usr/src/bashio     && curl -L -f -s "https://github.com/hassio-addons/bashio/archive/v${BASHIO_VERSION}.tar.gz"         | tar -xzf - --strip 1 -C /usr/src/bashio     && mv /usr/src/bashio/lib /usr/lib/bashio     && ln -s /usr/lib/bashio/bashio /usr/bin/bashio         && rm -rf /var/lib/apt/lists/*     && rm -rf /usr/src/*
 ---> Running in 4458f4ddde42
+ apt-get update

/bin/bash: line 1: apt-get: command not found `

**Comment by MartinHjelmare** [comment]
Wrong architecture maybe? Not sure.

**Comment by agners** [comment]
My attempt: https://github.com/home-assistant/addons/pull/2952

**Pull request closed without merging**
