### PR TITLE
letsencrypt: Add support for ClouDNS provider

### PR DESCRIPTION
**Pull request by tedski**
Adds support for ClouDNS provider for Let's Encrypt SSL certificates. Uses the certbot-dns-cloudns plugin.

### CODE REVIEW

**Comment by agners** [comment]
It seems there is a minor linter error which needs addressing.

probably also make sense to add documentation for this provider, along with the two authentication options (auth_id/sub_auth_id).

**Comment by agners** [comment]
Fixes: #1022

**Comment by tedski** [comment]
I see the pip dependency issue and will work on that today.

**Comment by tedski** [comment]
> It seems there is a minor linter error which needs addressing.
> 
> probably also make sense to add documentation for this provider, along with the two authentication options (auth_id/sub_auth_id).

Oops!  I missed the Example configs section.  Will update that.

**Comment by tedski** [comment]
Waiting on dep bump in https://github.com/inventage/certbot-dns-cloudns/pull/4

**Comment by tedski** [comment]
> Waiting on dep bump in [inventage/certbot-dns-cloudns#4](https://github.com/inventage/certbot-dns-cloudns/pull/4)

Dependency was updated to support newer acme versions.  We should be good to go now.

**Review by agners — APPROVED** [review]

**Comment by tedski** [comment]
I seem to have added the bot as a reviewer accidentally.  I'm not sure if this will block the merge process from any automation, but I don't seem to be able to remove the bot from the reviewers list.  Let me know if there's anything else I need to complete to get this merged.

**Comment by agners** [comment]
All good, sorry I missed merging this.

**Pull request merged**
