### PR TITLE
Add FreeDNS (Afraid.org) ACME Shell certs for LetsEncrypt

### PR DESCRIPTION
**Pull request by wernerhp**

### CODE REVIEW

**Comment by knifesk** [comment]
+1 on this.. How could we solve the checks?

**Comment by jflattery** [comment]
Pardon my ignorance but why limit this to FreeDNS/Afraid.org? ACME.sh would add support for otherwise unsupported DNS providers.

**Comment by jflattery** [comment]
Adding ACME.sh would be great as it could add support for otherwise unsupported DNS providers.

**Comment by wernerhp** [comment]
@jflattery TBH, I only implemented FreeDNS/Afraid.org, because that's what I needed.  Can of course add more providers as and when needed.

**Comment by wernerhp** [comment]
@jflattery TBH, I only implemented FreeDNS/Afraid.org, because that's what I needed.  Can of course add more providers as and when needed.

**Comment by homeassistant** [comment]
Hello @wernerhp,

When attempting to inspect the commits of your pull request for CLA signature status among all authors we encountered commit(s) which were not linked to a GitHub account, thus not allowing us to determine their status(es).

The commits that are missing a linked GitHub account are the following:

- [`6bab712a7840ea835e996dab46801961f4e5e0ca`](https:&#x2F;&#x2F;github.com&#x2F;home-assistant&#x2F;addons&#x2F;pull&#x2F;1736&#x2F;commits&#x2F;6bab712a7840ea835e996dab46801961f4e5e0ca) - This commit has something that looks like an email address (wpieterson@luno.com). Maybe try linking that to GitHub?.
- [`c125ef8695a311bbc045b165c76f2dd93c0ef69b`](https:&#x2F;&#x2F;github.com&#x2F;home-assistant&#x2F;addons&#x2F;pull&#x2F;1736&#x2F;commits&#x2F;c125ef8695a311bbc045b165c76f2dd93c0ef69b) - This commit has something that looks like an email address (wpieterson@luno.com). Maybe try linking that to GitHub?.
- [`e940d1f641da9236fcf11938e552bfdae9b87c79`](https:&#x2F;&#x2F;github.com&#x2F;home-assistant&#x2F;addons&#x2F;pull&#x2F;1736&#x2F;commits&#x2F;e940d1f641da9236fcf11938e552bfdae9b87c79) - This commit has something that looks like an email address (wpieterson@luno.com). Maybe try linking that to GitHub?.
- [`90baddcd61bc8a78a949deaf0588207b1b5f825d`](https:&#x2F;&#x2F;github.com&#x2F;home-assistant&#x2F;addons&#x2F;pull&#x2F;1736&#x2F;commits&#x2F;90baddcd61bc8a78a949deaf0588207b1b5f825d) - This commit has something that looks like an email address (wpieterson@luno.com). Maybe try linking that to GitHub?.

Unfortunately, **we are unable to accept this pull request until this situation is corrected.**

Here are your options:

1. If you had an email address set for the commit that simply wasn't linked to your GitHub account you can link that email now and it will retroactively apply to your commits. The simplest way to do this is to click the link to one of the above commits and look for a blue question mark in a blue circle in the top left. Hovering over that bubble will show you what email address you used. Clicking on that button will take you to your email address settings on GitHub. Just add the email address on that page and you're all set. GitHub has more information about this option [in their help center](https://help.github.com/articles/setting-your-email-in-git/#commits-on-github-arent-linking-to-my-account).

2. If you didn't use an email address at all, it was an invalid email, or it's one you can't link to your GitHub, you will need to change the authorship information of the commit and your global Git settings so this doesn't happen again going forward. GitHub provides some great instructions on how to change your authorship information [in their help center](https://help.github.com/articles/setting-your-email-in-git/).
   * If you only made a single commit you should be able to run
      ```
      git commit --amend --author="Author Name <email@address.com>"
      ```
      (substituting Author Name and email@address.com for your actual information) to set the authorship information.
   * If you made more than one commit and the commit with the missing authorship information is not the most recent one you have two options:
       1. You can re-create all commits missing authorship information. This is going to be the easiest solution for developers that aren't extremely confident in their Git and command line skills.
       2. You can use [this script](https://help.github.com/articles/changing-author-info/) that GitHub provides to rewrite history. **Please note:** this should be used only if you are very confident in your abilities and understand its impacts.
   * Whichever method you choose, I will come by to re-check the pull request once you push the fixes to this branch.

We apologize for this inconvenience, especially since it usually bites new contributors to Home Assistant. We hope you understand the need for us to protect ourselves and the great community we all have built legally. The best thing to come out of this is that you only need to fix this once and it benefits the entire Home Assistant and GitHub community.

Thanks, I look forward to checking this PR again soon! :heart:

**Comment by knifesk** [comment]
I see most of the errors are due to missing newline on some files.. maybe you can configure your IDE/Text editor to always add them if they're not there :)

**Comment by wernerhp** [comment]
I had a line missing in my `config.json`.  Sorted.

**Comment by knifesk** [comment]
hooray!!!

**Comment by acw0123** [comment]
Could you please also add support for hosting.de? See https://go-acme.github.io/lego/dns/hostingde/ or will that not work with this generic acme.sh extension?

**Comment by wernerhp** [comment]
@acw0123 It looks like `hosting.de` is supported by [`acmesh-official/acme.sh`](https://github.com/acmesh-official/acme.sh/blob/master/dnsapi/dns_hostingde.sh), so it should be simple to add it.

Would be nice to get the basic add-on merged in first and then expand to more providers as it is easier to consume when reviewing.

**Comment by acw0123** [comment]
Hi Werner,

Yes, I am very happy if it goes in as a basic add-on first. I agree that is easier. 
Thank you for considering hosting.de for a later addition.

Best regards,
Andrew

**Comment by samyun** [comment]
Is there a compelling reason to have two separate add-ons for Let's Encrypt certs? `acme_sh` and `letsencrypt`? On one hand, having the separate `acme_sh` add-on eliminates the risk of breaking existing users of `letsencrypt`, but on the other hand, people who are setting up for the first time might get confused why there's two add-ons that seem to do the same thing. 

It'd be good for one of the maintainers to chime in, but I'd have the following suggestions:
* Either fold `acme.sh` into the `letsencrypt` add-on, perhaps as a selectable option, or keep them separate but make a note in the `letsencrypt` docs to use `acme_sh` instead if `letsencrypt` doesn't support the DNS provider you want. Personally, I like the first option best.
* Instead of trying to support every provider that people want (which would probably get tiring), instead add a thing in the configuration to add custom exports, something like:
```
dns:
  provider: dns_freedns 
  exports: [
    FREEDNS_User: <username>
    FREEDNS_Password: <password>
 ]
```
  * this way, you can add a link to https://github.com/acmesh-official/acme.sh/wiki/dnsapi for the exports that people want to use instead of waiting for someone who wants to use a particular provider (e.g. me, who wants to use Azure), to go and make a PR to make it work.

**Comment by wernerhp** [comment]
> Is there a compelling reason to have two separate add-ons for Let's Encrypt certs? `acme_sh` and `letsencrypt`? On one hand, having the separate `acme_sh` add-on eliminates the risk of breaking existing users of `letsencrypt`, but on the other hand, people who are setting up for the first time might get confused why there's two add-ons that seem to do the same thing.

Well, both do Let's Encrypt, but the one uses Certbot and this one uses ACME.sh. This one has support for providers the other one doesn't. Adding this to the other one may create a wrong expectation of what is supported with ACME.sh.  I don't think there's anything wrong with having choice.


> ```
> dns:
>   provider: dns_freedns 
>   exports: [
>     FREEDNS_User: <username>
>     FREEDNS_Password: <password>
>  ]
> ``

Sure, we can look into this.

**Comment by jflattery** [comment]
My first thought is that it would be appropriate to leave them separate. As @wernerhp points out, the `letsencrypt` uses the official and recommended `Certbot` client, while this one uses just one of the [many](https://letsencrypt.org/docs/client-options/) available community clients. 

In either case, I think it would be a great idea to make ACME.sh, and perhaps other clients, available as choices for the user. Each client has it's pros and cons.

**Comment by acw0123** [comment]
Hi all

Any idea why this one is stuck? I thought it was submitted for inclusion. I’m still hoping to be able to use further enhancements (hosting.de) to it in the future as acme.sh supports far more DNS providers than the current letsencryot addon. 

Best regards 
A

**Comment by wernerhp** [comment]
No idea and don't know if it's appropriate to @mention anyone specific to approve it.  @homeassistant

**Comment by wernerhp** [comment]
Why s there still a cla-error tag?

**Comment by frenck** [comment]
I think it would be extremely confusing to add this to the core add-ons, we already have the let's encrypt add-on.

**Comment by wernerhp** [comment]
@frenck while they are functionally similar, the different backends (ACME.sh, certbot) have different configurations (challenges & arguments for instance) and support for different DNS providers.  Adding ACME.sh into the existing add-on might just make the documentation and configuring the add-on harder to understand as one would need to know which DNS provider is supported by which backend. Adding this to the other one may create a wrong expectation of what either of the two backends support.  I'm open to suggestions on how we can merge them cleanly.
We also have DuckDNS which provides both DNS and LetsEncrypt.

**Comment by frenck** [comment]
I don't think we should add this as a core add-on, mainly for the confusion it will cause.

**Comment by acw0123** [comment]
Any chance of getting it added as a 
Home Assistant Community Add-on 
instead of Official Core? Or any suggestions on how to get the breadth of dns supported in the existing one?

Best regards 
Andrew

**Comment by frenck** [comment]
> Any chance of getting it added as a
Home Assistant Community Add-on
instead of Official Core? Or any suggestions on how to get the breadth of dns supported in the existing one?

Anybody can publish add-ons on GitHub, that is no up to us, but up to you.

**Comment by ludeeus** [comment]
I agree with @frenck we should not add this to the core add-ons.
Thanks anyway :+1:

**Comment by wernerhp** [comment]
Anyone want to test? 

[Open your Home Assistant instance and show the add add-on repository dialog with a specific repository URL pre-filled.](https://my.home-assistant.io/redirect/supervisor_add_addon_repository/?repository_url=https%3A%2F%2Fgithub.com%2Fwernerhp%2Fha_addon_acme_sh)

**Comment by acw0123** [comment]
Hi Werner

I understand it is being rejected so not sure why we would test anything. If the plan is to make it available under the optional add-ons then I would be happy to try to test it with the following caveats:
- my DNS is provided by hosting.de one of the standard ACME extensions - so that’s the only one I could test end-to-end
- I used to say I was experienced with Linux (I started with 0.12 and later spent a few years using Gentoo before I got too lazy and switched to Debian & Co) but that was before the whole Container approach. I run my home assistant on a raspberry Pi using the ready made image the home assistant team provide (HassOS I think) so I may need an explanation how to get whatever we want to test into the container. 

Best regards 
AcW

**Comment by wernerhp** [comment]
@acw0123 Correct, it is not part of the core Add-ons.  As per the core devs recommendation I created my own addon which you can add to HA.  To do so, simply click the My Home Assistant Add Repository link above to add my repo, then search for and install Let's Encrypt with ACME.sh.  You can configure the add-on as per the [docs](https://github.com/wernerhp/ha_addon_acme_sh/blob/master/DOCS.md)
I took some suggestions from the comments on this PR and changed the code to allow you to export environment variables via the add-on config, so it should now work for all providers supported by ACME.sh, including hosting.de.

**Comment by acw0123** [comment]
Hi Werner,

Thank you very much. I tested your acme.sh addon with various domain names including wildcard domain names.

The AddOn works well. 

I used the guidance in https://github.com/acmesh-official/acme.sh/wiki/dnsapi#55-use-hostingde-api <https://github.com/acmesh-official/acme.sh/wiki/dnsapi#55-use-hostingde-api> to determine the right env variables to use for my provider.

I made use of the env variable DEBUG=1 (0 to 3)

Contrary to the acme.sh github documentation above I had to remove the quotes (‘) in the env variables (e.g. HOSTINGDE_APIKEY=xxx not ‘xxx’) to get it to work.

I suggest we try to have it added to the "Home Assistant Community Add-ons” as it supports far more providers than the letsencrypt addon - and covers all the ones that letsencrypt supports too, so it will be a useful alternative for many in the community.

Best regards,
AcW

**Comment by samyun** [comment]
+1 to ^ for me - I used Azure, and I also needed to remove the quotes in the env. 

Also looks like acme.sh switched to defaulting to zerossl, not LetsEncrypt, at some point in the last few months. Might be worth pointing that out in the docs. 

Doesn't look like this add on will auto-renew, right? Or does acme.sh automatically do that?

**Pull request closed without merging**
