### PR TITLE
ssh: Upgrades Home Assistant CLI to v4.9.0

### PR DESCRIPTION
**Pull request by frenck**
Release notes:

<https://github.com/home-assistant/cli/releases/tag/4.9.0>

### CODE REVIEW

**Review by ludeeus — APPROVED** [review]
Should wait with merge until a new Supervisor is pushed to the stable channel.

**Comment by frenck** [comment]
Why @ludeeus? Is there something breaking? It does add new commands, (that obviously do not work on systems that haven't upgraded). Considering the current version is 4.5.0 inside the add-on, lots of functionality for people isn't accessible right now either.

As for new functionality, that can be tested when running beta.

**Comment by ludeeus** [comment]
This bump includes 4.8, which is breaking for the "network" namespace <https://github.com/home-assistant/cli/pull/259>

**Comment by frenck** [comment]
Good point! 👍

**Pull request merged**
