### PR TITLE
Bump base images to 2022.02.0

### LINKED ISSUE #2373: Fatal error while loading config
### Describe the issue you are experiencing

The Addon fails while loading config

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Check Home Assistant configuration

### What is the version of the add-on?

3.9.0

### Steps to reproduce the issue

1. Start addon
2. be sad
3.
...

### Anything in the Supervisor logs that might be useful for us?

_No response_

### Anything in the add-on logs that might be useful for us?

```txt
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[22:30:02] INFO: Don't worry, this temporary installation is not overwriting your current one.
[22:30:02] INFO: Installing Home Assistant: stable...
[22:30:02] INFO: Please be patient, this might take a few minutes...
[22:31:16] INFO: Installed Home Assistant 2022.2.0
[22:31:16] INFO: Making a copy of your configuration for checking...
[22:31:19] INFO: Checking your configuration against this version...
[22:35:07] ERROR: The configuration check did not pass!
[22:35:07] ERROR: See the output below for more details.
[22:35:07] INFO: The full output has been written to /share/check_config.txt
Testing configuration at /tmp/config
INFO:homeassistant.helpers.storage:Migrating core.device_registry storage from 1.2 to 1.3
INFO:homeassistant.helpers.storage:Migrating core.entity_registry storage from 1.4 to 1.5
WARNING:homeassistant.components.statistics.sensor:The configuration parameter 'state_characteristic' will become mandatory in a future release of the statistics integration. Please add 'state_characteristic: mean' to the configuration of sensor 'Bathroom Humidity Stats' to keep the current behavior. Read the documentation for further details: https://www.home-assistant.io/integrations/statistics/
Fatal error while loading config: [Errno 2] No such file or directory: '/usr/local/lib/python3.9/site-packages/multidict-6.0.2.dist-info/METADATA'
Failed config
  General Errors: 
    - [Errno 2] No such file or directory: '/usr/local/lib/python3.9/site-packages/multidict-6.0.2.dist-info/METADATA'

Successful config (partial)
s6-svscanctl: fatal: unable to control /var/run/s6/services: supervisor not listening
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Kisty**
Fixes #2373 #2377

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
Please update the changelog and bump the version number of the add-on as well.

**Comment by Kisty** [comment]
Done @frenck

**Comment by Kisty** [comment]
Had a chance to review this yet?

**Comment by frenck** [comment]
@Kisty Sorry, I missed the notification I guess. Started the CI

**Comment by Daneish** [comment]
Thanks for the update! Unfortunately after updating, the same errors reported in https://github.com/home-assistant/addons/issues/2373 and https://github.com/home-assistant/addons/issues/2377 still remain for me.

Error message: [Errno 2] No such file or directory: '/usr/local/lib/python3.9/site-packages/multidict-6.0.2.dist-info/METADATA'

I'm running:
Check Home Assistant Configuration: 3.10.0
HA Core: 2022.2.8 (I also had the issue on 2022.2.7)
HA OS: 7.4

I'm new to reporting feedback and wasn't sure where the best place to post this, as the issues were closed, but can update #2373 or raise a new one if that is more appropriate.

**Pull request merged**
