### PR TITLE
Fix deCONZ/Phoscon Ingress access when using FQDN

### LINKED ISSUE #947: Deconz through ingress has an unselectable system
I have updated to Deconz 5.0 and HA 103.4 HassOS 3.7 and when I use the Deconz addin through ingress I get a page where I can see my Conbee stick but not select it (it is grayed out):
image

Everything else that was configured before upgrading to version 4 of Deconz still works, I just cannot use the deconz web interface to add new things or change config.

### LINKED ISSUE #1677: After upgrade to deCONZ 6.5 the phoscon web app does not work any more
I click on deconz / phoscon. Normally it would launch the login dialog and after login the web app.
Now there is just the phoscon logo at the top. When I click onto it, a loading screen starts: "Bitte warten, während die Suche nach Gateways durchgeführt wird." --> Wait while looking for gateways. That's it. No more.

The other deconz-VNC-App seems to work.

### LINKED ISSUE #2172: deCONZ: Phoscon Web App Login only visible when using IP-Addr as an URL via Ingress
## The problem

My vanilla hass.io instance ran smothly from 192.168.2.10:8123 (your address my vary). 
To make it it nicer, I set up a dns entry that would link ha.mydomain.tld to the address and then use http://ha.mydomain.tld:8123 just because.

Now when I use the domain url (does NOT matter if http or https), the login field of deCONZ does NOT show up / you can't choose the stick.

Since I would enforce SSL and the domain in the next step, deCONZ can't be configured any more properly.

## Environment
- Raspberry PIE 4 / 8GB / 64 Bit Image
- Home Assistant 2021.8.8 , but Problem exists at least since 2021.6 or 5 (not tried that before)
- ConBeeUSB II Stick
- Fresh Install is the same

## Problem-relevant configuration
There is no config that causes that except when I use a domain name instead of an IP Address

## Traceback/Error logs
I can't find log errors on the server. It might fail in the browser but looking at the Web-Console reveals nothing to my knowledge (so no error in the JS-Console for Example)

## Additional information
Don't know anything else.
I've included a screenshot side by side of the Browser display with IP-Address and with Domain-Name. 
Screenshot - no Login Side by Side

### PR DESCRIPTION
**Pull request by tannyl**
This fixes the problem with not being able to use the Phoscon App interface via Ingress when using a fully qualified domain name.

The Phoscon Apps javascript code is, in lack of better words, a bit wonky and contains errors, but with this fix, Ingress should at least work when using both IP and domain name to access Home Assistant.

The fix helps the App find the correct gateway and also stops it from trying to find other gateways.

It also improves the way "subnet probing" is stopped.

I have tested this by applying the fixes directly to the nginx.conf file in the docker container and everything seems to work as it should.

Resolves #2172
Resolves  #947
Resolves #1677

Most likely related to  #1521 and #2054

### CODE REVIEW

**Comment by pvizeli** [comment]
Change log + bump version with 0.0.1

thanks

**Comment by tannyl** [comment]
@pvizeli updated version and changelog. :smiley:

**Comment by tannyl** [comment]
@pvizeli anything else that needs to be done?

**Comment by tannyl** [comment]
@klaasnicolaas @frenck
Maybe one or both of you would take a look at this? Thanks.

**Comment by frenck** [comment]
@tannyl Please don't ping people at random for reviews. That is not something we want in this org, to prevent people from being flooded with pings. Additionally, I cannot review it now, as I don't want such ping behavior to work/be rewarded with a review. Hope you'll understand (nothing personal). There are 800+  PRs open across the org, this isn't the oldest either.

**Comment by tannyl** [comment]
Sorry about that @frenck 

It was not "at random" though. I saw that you and klassnicolaas where some of the last ones to add changes to this addon, thus I expected you might be the ones "in charge of it". I will remember not to ping like this again and I have not taken anything personal.

**Review by mdegat01 — APPROVED** [review]
Wow, great work. I can merge just need you to rebase and resolve the conflict with `config.yaml`. Believe you just need to add `---` as a formatter did that in a later PR.

**Comment by tannyl** [comment]
@mdegat01 sounds great. I have fixed `config.yaml` and it should be ready to go no.

**Comment by mdegat01** [comment]
Thanks @tannyl 👍

**Pull request merged**
