### PR TITLE
Support CNAME records

### PR DESCRIPTION
**Pull request by ocalvo**
Follow up to #2410

### CODE REVIEW

**Review by mdegat01 — APPROVED** [review]
@ocalvo I'm fine with this but you never answered my question on the last PR [here](https://github.com/home-assistant/addons/pull/2410#pullrequestreview-955528693). Basically just want to know if this note in the DNSMasq documation on cnames is something we should worry about:
> Provide an alias for a "local" DNS name. Note that this _only_ works
> for targets which are names from DHCP or /etc/hosts. Give host
> "bert" another name, bertrand
> cname=bertand,bert

The emphasis on "only" here suggests it is something DNSMasq users are frequently tripped up by. Should we note the same in the documentation of this option?

**Comment by ocalvo** [comment]
ping, do not close

**Comment by ocalvo** [comment]
> @ocalvo I'm fine with this but you never answered my question on the last PR [here](https://github.com/home-assistant/addons/pull/2410#pullrequestreview-955528693). Basically just want to know if this note in the DNSMasq documation on cnames is something we should worry about:
> 
> > Provide an alias for a "local" DNS name. Note that this _only_ works
> > for targets which are names from DHCP or /etc/hosts. Give host
> > "bert" another name, bertrand
> > cname=bertand,bert
> 
> The emphasis on "only" here suggests it is something DNSMasq users are frequently tripped up by. Should we note the same in the documentation of this option?

Added the same note in the DOCS.

**Comment by ocalvo** [comment]
Keep alive

**Comment by ocalvo** [comment]
@frenck this has been open for months and closed at least 2 times becuase time passes. Can we add a rule that if the PR has a review and comments that the bot does not closes the PR?

**Comment by ocalvo** [comment]
Keep alive

**Review by mdegat01 — CHANGES_REQUESTED** [review]
Need to bump the version in `config.yaml` to `1.5.0`, you only bumped the changelog. Then I can merge it. Sorry for the delay.

**Comment by ocalvo** [comment]
> Need to bump the version in `config.yaml` to `1.5.0`, you only bumped the changelog. Then I can merge it. Sorry for the delay.

Done

**Review by mdegat01 — APPROVED** [review]

**Comment by mdegat01** [comment]
Thanks @ocalvo 👍

**Pull request merged**
