### PR TITLE
mariadb: Increase timeout for MariaDB shutdown

### LINKED ISSUE #3566: MariaDB is not starting after update to 2.7.0
### Describe the issue you are experiencing

```
[00:31:12] INFO: Starting MariaDB
2024-04-16  0:31:12 0 [Note] Starting MariaDB 10.11.6-MariaDB source revision fecd78b83785d5ae96f2c6ff340375be803cd299 as process 13206
2024-04-16  0:31:13 0 [Note] InnoDB: Compressed tables use zlib 1.3.1
2024-04-16  0:31:13 0 [Note] InnoDB: Number of transaction pools: 1
2024-04-16  0:31:13 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
2024-04-16  0:31:13 0 [Note] mysqld: O_TMPFILE is not supported on /var/tmp (disabling future attempts)
2024-04-16  0:31:13 0 [Note] InnoDB: Using Linux native AIO
2024-04-16  0:31:13 0 [Note] InnoDB: Initializing buffer pool, total size = 128.000MiB, chunk size = 2.000MiB
2024-04-16  0:31:13 0 [Note] InnoDB: Completed initialization of buffer pool
2024-04-16  0:31:13 0 [Note] InnoDB: File system buffers for log disabled (block size=512 bytes)
2024-04-16  0:31:13 0 [ERROR] InnoDB: Upgrade after a crash is not supported. The redo log was created with MariaDB 10.6.8. You must start up and shut down MariaDB 10.7 or earlier.
2024-04-16  0:31:13 0 [ERROR] InnoDB: Plugin initialization aborted with error Generic error
2024-04-16  0:31:13 0 [Note] InnoDB: Starting shutdown...
2024-04-16  0:31:14 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
2024-04-16  0:31:14 0 [Note] Plugin 'FEEDBACK' is disabled.
2024-04-16  0:31:14 0 [ERROR] Unknown/unsupported storage engine: InnoDB
2024-04-16  0:31:14 0 [ERROR] Aborting
[00:31:14] INFO: Service mariadb exited with code 1 (by signal 0)
```

what should i do ?

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

MariaDB

### What is the version of the add-on?

2.7.0

### Steps to reproduce the issue

1.update from 2.6.1 to 2.7.0

## System Information

version | core-2024.4.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.25-haos
arch | x86_64
timezone | Europe/Rome
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4885
Installed Version | 1.34.0
Stage | running
Available Repositories | 1402
Downloaded Repositories | 17

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.2
-- | --
update_channel | stable
supervisor_version | supervisor-2024.04.0
agent_version | 1.6.0
docker_version | 25.0.5
disk_total | 30.8 GB
disk_used | 7.4 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.8.0), Terminal & SSH (9.13.0), Mosquitto broker (6.4.0), Zigbee2MQTT (1.36.1-1), MariaDB (2.7.0), Samba share (12.3.1), Ring-MQTT with Video Streaming (5.6.3), Studio Code Server (5.15.0), Node-RED (17.0.11)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 8
views | 9
mode | storage

</details>

<details><summary>Sonoff</summary>

version | 3.6.0 (8dd8af9)
-- | --
cloud_online | 1 / 2
local_online | 1 / 1

</details>

### Anything in the Supervisor logs that might be useful for us?

```txt
2024-04-15 21:26:24.079 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
2024-04-15 21:56:24.573 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
2024-04-15 22:19:08.481 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state running
2024-04-15 22:19:08.482 INFO (MainThread) [supervisor.resolution.checks.base] Run check for ipv4_connection_problem/system
2024-04-15 22:19:08.482 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_ipv6_error/dns_server
2024-04-15 22:19:08.543 INFO (MainThread) [supervisor.resolution.checks.base] Run check for security/core
2024-04-15 22:19:08.544 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_failed/dns_server
2024-04-15 22:19:08.545 INFO (MainThread) [supervisor.resolution.checks.base] Run check for pwned/addon
2024-04-15 22:19:08.545 INFO (MainThread) [supervisor.resolution.checks.base] Run check for multiple_data_disks/system
2024-04-15 22:19:08.546 INFO (MainThread) [supervisor.resolution.checks.base] Run check for trust/supervisor
2024-04-15 22:19:08.563 INFO (MainThread) [supervisor.resolution.checks.base] Run check for free_space/system
2024-04-15 22:19:08.563 INFO (MainThread) [supervisor.resolution.checks.base] Run check for docker_config/system
2024-04-15 22:19:08.564 INFO (MainThread) [supervisor.resolution.check] System checks complete
2024-04-15 22:19:08.564 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state running
2024-04-15 22:19:09.018 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
2024-04-15 22:19:09.018 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state running
2024-04-15 22:19:09.019 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
2024-04-15 22:23:28.968 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
2024-04-15 22:24:46.515 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/tsightler/ring-mqtt-ha-addon repository
2024-04-15 22:24:46.523 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
2024-04-15 22:24:46.531 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/zigbee2mqtt/hassio-zigbee2mqtt repository
2024-04-15 22:24:46.549 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository
2024-04-15 22:24:46.567 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
2024-04-15 22:24:50.607 INFO (MainThread) [supervisor.store] Loading add-ons from store: 81 all - 0 new - 0 remove
2024-04-15 22:24:50.608 INFO (MainThread) [supervisor.store] Loading add-ons from store: 81 all - 0 new - 0 remove
2024-04-15 22:26:25.054 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
2024-04-15 22:56:25.599 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
2024-04-15 23:19:09.061 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state running
2024-04-15 23:19:09.061 INFO (MainThread) [supervisor.resolution.checks.base] Run check for ipv4_connection_problem/system
2024-04-15 23:19:09.061 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_ipv6_error/dns_server
2024-04-15 23:19:09.171 INFO (MainThread) [supervisor.resolution.checks.base] Run check for security/core
2024-04-15 23:19:09.173 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_failed/dns_server
2024-04-15 23:19:09.194 INFO (MainThread) [supervisor.resolution.checks.base] Run check for pwned/addon
2024-04-15 23:19:09.214 INFO (MainThread) [supervisor.resolution.checks.base] Run check for multiple_data_disks/system
2024-04-15 23:19:09.214 INFO (MainThread) [supervisor.resolution.checks.base] Run check for trust/supervisor
2024-04-15 23:19:09.231 INFO (MainThread) [supervisor.resolution.checks.base] Run check for free_space/system
2024-04-15 23:19:09.232 INFO (MainThread) [supervisor.resolution.checks.base] Run check for docker_config/system
2024-04-15 23:19:09.233 INFO (MainThread) [supervisor.resolution.check] System checks complete
2024-04-15 23:19:09.233 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state running
2024-04-15 23:19:09.598 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
2024-04-15 23:19:09.598 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state running
2024-04-15 23:19:09.599 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
2024-04-15 23:26:26.187 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
2024-04-15 23:30:55.827 INFO (MainThread) [supervisor.host.info] Updating local host information
2024-04-15 23:30:57.086 INFO (MainThread) [supervisor.host.services] Updating service information
2024-04-15 23:30:57.100 INFO (MainThread) [supervisor.host.network] Updating local network information
2024-04-15 23:30:57.443 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
2024-04-15 23:30:57.459 INFO (MainThread) [supervisor.host.manager] Host information reload completed
2024-04-15 23:56:26.658 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
2024-04-16 00:02:20.672 INFO (MainThread) [supervisor.backups.manager] Backup 7aa30de8 starting stage addon_repositories
2024-04-16 00:02:20.673 INFO (MainThread) [supervisor.backups.manager] Backup 7aa30de8 starting stage docker_config
2024-04-16 00:02:20.673 INFO (MainThread) [supervisor.backups.manager] Creating new partial backup with slug 7aa30de8
2024-04-16 00:02:20.688 INFO (MainThread) [supervisor.backups.manager] Backup 7aa30de8 starting stage addons
2024-04-16 00:02:27.107 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on core_mariadb
2024-04-16 00:02:44.512 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon core_mariadb
2024-04-16 00:02:47.314 INFO (MainThread) [supervisor.backups.manager] Backup 7aa30de8 starting stage finishing_file
2024-04-16 00:02:47.325 INFO (MainThread) [supervisor.backups.manager] Creating partial backup with slug 7aa30de8 completed
2024-04-16 00:02:47.330 INFO (MainThread) [supervisor.docker.addon] Updating image homeassistant/amd64-addon-mariadb:2.6.1 to homeassistant/amd64-addon-mariadb:2.7.0
2024-04-16 00:02:47.330 INFO (MainThread) [supervisor.docker.interface] Downloading docker image homeassistant/amd64-addon-mariadb with tag 2.7.0.
2024-04-16 00:03:21.486 INFO (SyncWorker_2) [supervisor.docker.manager] Stopping addon_core_mariadb application
2024-04-16 00:03:51.108 INFO (SyncWorker_2) [supervisor.docker.manager] Cleaning addon_core_mariadb application
2024-04-16 00:03:52.072 INFO (MainThread) [supervisor.addons.addon] Add-on 'core_mariadb' successfully updated
2024-04-16 00:03:53.461 INFO (SyncWorker_0) [supervisor.docker.manager] Cleanup images: ['homeassistant/amd64-addon-mariadb:2.6.1']
2024-04-16 00:04:05.052 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-mariadb with version 2.7.0
2024-04-16 00:04:05.102 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/tsightler/ring-mqtt-ha-addon repository
2024-04-16 00:04:05.162 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
2024-04-16 00:04:05.210 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/zigbee2mqtt/hassio-zigbee2mqtt repository
2024-04-16 00:04:05.263 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository
2024-04-16 00:04:05.271 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
2024-04-16 00:04:05.440 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
2024-04-16 00:04:28.748 INFO (MainThread) [supervisor.store] Loading add-ons from store: 81 all - 0 new - 0 remove
2024-04-16 00:04:28.749 INFO (MainThread) [supervisor.store] Loading add-ons from store: 81 all - 0 new - 0 remove
2024-04-16 00:10:50.989 INFO (SyncWorker_3) [supervisor.docker.manager] Restarting homeassistant
2024-04-16 00:13:21.818 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
2024-04-16 00:14:35.939 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state running
2024-04-16 00:14:37.075 INFO (MainThread) [supervisor.homeassistant.core] Home Assistant Core state changed to NOT_RUNNING
2024-04-16 00:14:37.466 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
2024-04-16 00:16:14.236 INFO (MainThread) [supervisor.homeassistant.core] Home Assistant Core state changed to RUNNING
2024-04-16 00:16:14.236 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
2024-04-16 00:19:09.623 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state running
2024-04-16 00:19:09.623 INFO (MainThread) [supervisor.resolution.checks.base] Run check for ipv4_connection_problem/system
2024-04-16 00:19:09.623 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_ipv6_error/dns_server
2024-04-16 00:19:09.683 INFO (MainThread) [supervisor.resolution.checks.base] Run check for security/core
2024-04-16 00:19:09.685 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_failed/dns_server
2024-04-16 00:19:09.686 INFO (MainThread) [supervisor.resolution.checks.base] Run check for pwned/addon
2024-04-16 00:19:09.686 INFO (MainThread) [supervisor.resolution.checks.base] Run check for multiple_data_disks/system
2024-04-16 00:19:09.687 INFO (MainThread) [supervisor.resolution.checks.base] Run check for trust/supervisor
2024-04-16 00:19:09.711 INFO (MainThread) [supervisor.resolution.checks.base] Run check for free_space/system
2024-04-16 00:19:09.711 INFO (MainThread) [supervisor.resolution.checks.base] Run check for docker_config/system
2024-04-16 00:19:09.712 INFO (MainThread) [supervisor.resolution.check] System checks complete
2024-04-16 00:19:09.712 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state running
2024-04-16 00:19:10.040 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
2024-04-16 00:19:10.042 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state running
2024-04-16 00:19:10.042 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
2024-04-16 00:23:29.551 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
2024-04-16 00:26:27.127 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
2024-04-16 00:27:28.022 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from core_ssh
2024-04-16 00:27:28.029 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from core_ssh
2024-04-16 00:27:28.035 INFO (MainThread) [supervisor.api.middleware.security] /host/info access from core_ssh
2024-04-16 00:27:28.042 INFO (MainThread) [supervisor.api.middleware.security] /core/info access from core_ssh
```

### Anything in the add-on logs that might be useful for us?

```txt
2024-04-16  0:35:39 0 [Note] InnoDB: Completed initialization of buffer pool
2024-04-16  0:35:39 0 [Note] InnoDB: File system buffers for log disabled (block size=512 bytes)
2024-04-16  0:35:39 0 [ERROR] InnoDB: Upgrade after a crash is not supported. The redo log was created with MariaDB 10.6.8. You must start up and shut down MariaDB 10.7 or earlier.
2024-04-16  0:35:39 0 [ERROR] InnoDB: Plugin initialization aborted with error Generic error
2024-04-16  0:35:39 0 [Note] InnoDB: Starting shutdown...
2024-04-16  0:35:39 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
2024-04-16  0:35:39 0 [Note] Plugin 'FEEDBACK' is disabled.
2024-04-16  0:35:39 0 [ERROR] Unknown/unsupported storage engine: InnoDB
2024-04-16  0:35:39 0 [ERROR] Aborting
[00:35:39] INFO: Service mariadb exited with code 1 (by signal 0)
[00:35:40] INFO: Starting MariaDB
2024-04-16  0:35:40 0 [Note] Starting MariaDB 10.11.6-MariaDB source revision fecd78b83785d5ae96f2c6ff340375be803cd299 as process 15698
2024-04-16  0:35:41 0 [Note] InnoDB: Compressed tables use zlib 1.3.1
2024-04-16  0:35:41 0 [Note] InnoDB: Number of transaction pools: 1
2024-04-16  0:35:41 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
2024-04-16  0:35:41 0 [Note] mysqld: O_TMPFILE is not supported on /var/tmp (disabling future attempts)
2024-04-16  0:35:41 0 [Note] InnoDB: Using Linux native AIO
2024-04-16  0:35:41 0 [Note] InnoDB: Initializing buffer pool, total size = 128.000MiB, chunk size = 2.000MiB
2024-04-16  0:35:41 0 [Note] InnoDB: Completed initialization of buffer pool
2024-04-16  0:35:41 0 [Note] InnoDB: File system buffers for log disabled (block size=512 bytes)
2024-04-16  0:35:41 0 [ERROR] InnoDB: Upgrade after a crash is not supported. The redo log was created with MariaDB 10.6.8. You must start up and shut down MariaDB 10.7 or earlier.
2024-04-16  0:35:41 0 [ERROR] InnoDB: Plugin initialization aborted with error Generic error
2024-04-16  0:35:41 0 [Note] InnoDB: Starting shutdown...
2024-04-16  0:35:41 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
2024-04-16  0:35:41 0 [Note] Plugin 'FEEDBACK' is disabled.
2024-04-16  0:35:41 0 [ERROR] Unknown/unsupported storage engine: InnoDB
2024-04-16  0:35:41 0 [ERROR] Aborting
[00:35:41] INFO: Service mariadb exited with code 1 (by signal 0)
[00:35:43] INFO: Starting MariaDB
2024-04-16  0:35:43 0 [Note] Starting MariaDB 10.11.6-MariaDB source revision fecd78b83785d5ae96f2c6ff340375be803cd299 as process 15719
2024-04-16  0:35:43 0 [Note] InnoDB: Compressed tables use zlib 1.3.1
2024-04-16  0:35:43 0 [Note] InnoDB: Number of transaction pools: 1
2024-04-16  0:35:43 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
2024-04-16  0:35:43 0 [Note] mysqld: O_TMPFILE is not supported on /var/tmp (disabling future attempts)
2024-04-16  0:35:43 0 [Note] InnoDB: Using Linux native AIO
2024-04-16  0:35:43 0 [Note] InnoDB: Initializing buffer pool, total size = 128.000MiB, chunk size = 2.000MiB
2024-04-16  0:35:43 0 [Note] InnoDB: Completed initialization of buffer pool
2024-04-16  0:35:43 0 [Note] InnoDB: File system buffers for log disabled (block size=512 bytes)
2024-04-16  0:35:43 0 [ERROR] InnoDB: Upgrade after a crash is not supported. The redo log was created with MariaDB 10.6.8. You must start up and shut down MariaDB 10.7 or earlier.
2024-04-16  0:35:43 0 [ERROR] InnoDB: Plugin initialization aborted with error Generic error
2024-04-16  0:35:43 0 [Note] InnoDB: Starting shutdown...
2024-04-16  0:35:43 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
2024-04-16  0:35:43 0 [Note] Plugin 'FEEDBACK' is disabled.
2024-04-16  0:35:43 0 [ERROR] Unknown/unsupported storage engine: InnoDB
2024-04-16  0:35:43 0 [ERROR] Aborting
[00:35:44] INFO: Service mariadb exited with code 1 (by signal 0)
[00:35:45] INFO: Starting MariaDB
2024-04-16  0:35:45 0 [Note] Starting MariaDB 10.11.6-MariaDB source revision fecd78b83785d5ae96f2c6ff340375be803cd299 as process 15740
2024-04-16  0:35:45 0 [Note] InnoDB: Compressed tables use zlib 1.3.1
2024-04-16  0:35:45 0 [Note] InnoDB: Number of transaction pools: 1
2024-04-16  0:35:45 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
2024-04-16  0:35:45 0 [Note] mysqld: O_TMPFILE is not supported on /var/tmp (disabling future attempts)
2024-04-16  0:35:45 0 [Note] InnoDB: Using Linux native AIO
2024-04-16  0:35:45 0 [Note] InnoDB: Initializing buffer pool, total size = 128.000MiB, chunk size = 2.000MiB
2024-04-16  0:35:45 0 [Note] InnoDB: Completed initialization of buffer pool
2024-04-16  0:35:45 0 [Note] InnoDB: File system buffers for log disabled (block size=512 bytes)
2024-04-16  0:35:45 0 [ERROR] InnoDB: Upgrade after a crash is not supported. The redo log was created with MariaDB 10.6.8. You must start up and shut down MariaDB 10.7 or earlier.
2024-04-16  0:35:45 0 [ERROR] InnoDB: Plugin initialization aborted with error Generic error
2024-04-16  0:35:45 0 [Note] InnoDB: Starting shutdown...
2024-04-16  0:35:45 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
2024-04-16  0:35:45 0 [Note] Plugin 'FEEDBACK' is disabled.
2024-04-16  0:35:45 0 [ERROR] Unknown/unsupported storage engine: InnoDB
2024-04-16  0:35:45 0 [ERROR] Aborting
[00:35:46] INFO: Service mariadb exited with code 1 (by signal 0)
[00:35:47] INFO: Starting MariaDB
2024-04-16  0:35:47 0 [Note] Starting MariaDB 10.11.6-MariaDB source revision fecd78b83785d5ae96f2c6ff340375be803cd299 as process 15763
2024-04-16  0:35:47 0 [Note] InnoDB: Compressed tables use zlib 1.3.1
2024-04-16  0:35:47 0 [Note] InnoDB: Number of transaction pools: 1
2024-04-16  0:35:47 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
2024-04-16  0:35:47 0 [Note] mysqld: O_TMPFILE is not supported on /var/tmp (disabling future attempts)
2024-04-16  0:35:47 0 [Note] InnoDB: Using Linux native AIO
2024-04-16  0:35:47 0 [Note] InnoDB: Initializing buffer pool, total size = 128.000MiB, chunk size = 2.000MiB
2024-04-16  0:35:47 0 [Note] InnoDB: Completed initialization of buffer pool
2024-04-16  0:35:47 0 [Note] InnoDB: File system buffers for log disabled (block size=512 bytes)
2024-04-16  0:35:47 0 [ERROR] InnoDB: Upgrade after a crash is not supported. The redo log was created with MariaDB 10.6.8. You must start up and shut down MariaDB 10.7 or earlier.
2024-04-16  0:35:47 0 [ERROR] InnoDB: Plugin initialization aborted with error Generic error
2024-04-16  0:35:47 0 [Note] InnoDB: Starting shutdown...
2024-04-16  0:35:48 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
2024-04-16  0:35:48 0 [Note] Plugin 'FEEDBACK' is disabled.
2024-04-16  0:35:48 0 [ERROR] Unknown/unsupported storage engine: InnoDB
2024-04-16  0:35:48 0 [ERROR] Aborting
[00:35:48] INFO: Service mariadb exited with code 1 (by signal 0)
[00:35:49] INFO: Starting MariaDB
2024-04-16  0:35:49 0 [Note] Starting MariaDB 10.11.6-MariaDB source revision fecd78b83785d5ae96f2c6ff340375be803cd299 as process 15784
2024-04-16  0:35:50 0 [Note] InnoDB: Compressed tables use zlib 1.3.1
2024-04-16  0:35:50 0 [Note] InnoDB: Number of transaction pools: 1
2024-04-16  0:35:50 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
2024-04-16  0:35:50 0 [Note] mysqld: O_TMPFILE is not supported on /var/tmp (disabling future attempts)
2024-04-16  0:35:50 0 [Note] InnoDB: Using Linux native AIO
2024-04-16  0:35:50 0 [Note] InnoDB: Initializing buffer pool, total size = 128.000MiB, chunk size = 2.000MiB
2024-04-16  0:35:50 0 [Note] InnoDB: Completed initialization of buffer pool
2024-04-16  0:35:50 0 [Note] InnoDB: File system buffers for log disabled (block size=512 bytes)
2024-04-16  0:35:50 0 [ERROR] InnoDB: Upgrade after a crash is not supported. The redo log was created with MariaDB 10.6.8. You must start up and shut down MariaDB 10.7 or earlier.
2024-04-16  0:35:50 0 [ERROR] InnoDB: Plugin initialization aborted with error Generic error
2024-04-16  0:35:50 0 [Note] InnoDB: Starting shutdown...
2024-04-16  0:35:50 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
2024-04-16  0:35:50 0 [Note] Plugin 'FEEDBACK' is disabled.
2024-04-16  0:35:51 0 [ERROR] Unknown/unsupported storage engine: InnoDB
2024-04-16  0:35:51 0 [ERROR] Aborting
[00:35:52] INFO: Service mariadb exited with code 1 (by signal 0)
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by agners**
Currently, when MariaDB takes longer than 20s to shutdown, Docker will simply kill it. This can be problematic on upgrade, as the new MariaDB version cannot handle a not cleanly shutdown MariaDB (see #3566).

Increase the timeout of the container shutdown to 60s. Also define a per-service kill timeout for mariadb-core. This is largely optional, and essentially leads to the same outcome if MariaDB takes even longer (it will get killed, one way or another). But by defining this as part of the s6 service makes sure that the add-on log itself shows that MariaDB had to be killed, and makes sure the rest of the s6 service tree gets a chance to shutdown gracefully still:

```
[09:29:37] INFO: Service mariadb exited with code 256 (by signal 9) s6-rc: info: service mariadb-core successfully stopped s6-rc: info: service mariadb-pre: stopping
...
```

The 18s timeout of S6_SERVICES_GRACETIME seems to apply for legacy services only which are no longer used in this add-on. So drop this definition.

Fixes #3566

### CODE REVIEW

**Comment by lmagyar** [comment]
> @lmagyar review welcome 😄

Maybe increase it even further? 300 and 295000???

**Comment by lmagyar** [comment]
Maybe add a note to the beginning of the changelog, to "restart the addon before upgrade if the current version is lower than 2.7.1", and delete it a few month later.

**Comment by agners** [comment]
I was actually considering a bit higher value too :thinking: . I guess we should not make too much assumption of how long this takes. It also doesn't hurt much... If it takes long... well that is what it takes :sweat_smile: 

Increased to 5 minutes.

**Comment by agners** [comment]
> Maybe add a note to the beginning of the changelog, to "restart the addon before upgrade if the current version is lower than 2.7.1", and delete it a few ~month~ version later.

I've added a comment. However, I only mention "lower than 2.7.0 only": We don't do a major bump, so even if 2.7.0 fails to terminate gracefully, the problem won't appear as 2.7.1 will be able to recover just like 2.7.0 will be.

**Comment by lmagyar** [comment]
Yes, you are right, "version is lower than 2.7.0" should be fine:
- even if 2.7.0 shutdown fails, 2.7.1 has the same MariaDB version, so no problem to recover, no need to prior restart
- 2.7.0 had only a few days to run, it has a good chance to shutdown correctly

**Review by mdegat01 — APPROVED** [review]
I wonder if there's some way to get s6 to run a script when it does do kill. It would be nice if it could make a sentry issue when that happens so we can get a sense of whether we picked the right value or not

**Comment by agners** [comment]
> I wonder if there's some way to get s6 to run a script when it does do kill. It would be nice if it could make a sentry issue when that happens so we can get a sense of whether we picked the right value or not

The finish script has the exit code, we can do things based on that (see PR description, that INFO line is printed by the finish script). The exit code of the container should be 137 for this case, as we use the regular "exit code when killed by signal" logic (128 + signal).

**Pull request merged**
