### PR TITLE
Update DOCS.md

### PR DESCRIPTION
**Pull request by Mariusthvdb**
change to the new (version 11.0.0) homeassistant folder

### CODE REVIEW

**Comment by frenck** [comment]
Converting to draft, as we are currently re-considering this change.

**Comment by Mariusthvdb** [comment]
ok, sorry, I wasnt aware.. 
had posted this for some clarification https://community.home-assistant.io/t/samba-add-on-changed-config-to-homeassistant/639230 but if you reconsider that wont be the case..

**Comment by frenck** [comment]
> had posted this for some clarification [community.home-assistant.io/t/samba-add-on-changed-config-to-homeassistant/639230](https://community.home-assistant.io/t/samba-add-on-changed-config-to-homeassistant/639230) but if you reconsider that wont be the case..

I do not understand that post. This is not designed as a user-facing change. `/config` is just as normal.

**Comment by boheme61** [comment]
Maybe you could just add a symlink in / or /supervisor , and add to smb.gtp1 -file , in the supervisor-folder

[share]
follow symlinks = yes

**Comment by langestefan** [comment]
> I do not understand that post. This is not designed as a user-facing change. `/config` is just as normal. The share name simply changed to make a clear difference between the addon configuration (newly added, and being rolled out right now) and Home Assistant configuration.

This is a user facing change. This broke the network share of everyone using the samba addon, which must now mount `homeassistant` instead of `config`.

**Comment by frenck** [comment]
Replaced by #3311

**Pull request closed without merging**
