### PR TITLE
deCONZ 2.16.1 (stable)

### PR DESCRIPTION
**Pull request by klaasnicolaas**
Bump deCONZ version to [2.16.01](https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/v2.16.1)

### CODE REVIEW

**Review by christian1986 — APPROVED** [review]

**Review by thomas-svrts — APPROVED** [review]

**Comment by matteos1** [comment]
when there will be update deCONZ 2.16.1 (stable) addon?

**Comment by klaasnicolaas** [comment]
When someone merges this PR 😅

**Comment by matteos1** [comment]
When? 😜

**Comment by popy2k14** [comment]
Please merge!
The previous one with decont 2.15.3 has a serious bug.
thx

**Review by frenck — APPROVED** [review]
Thanks, @klaasnicolaas 👍

**Pull request merged**
