### PR TITLE
Update nginx.conf.gtpl to suppress: 'listen ... http2' directive is deprecated

### PR DESCRIPTION
**Pull request by RonnieDilli**
…eprecated.

This small changed update the code to use the "http2" directive and fixes the issue #3791.
-----
Changed this:
> listen 443 ssl http2;

To this:
> listen 443 ssl;
> http2 on;
-----
Source: https://www.nginx.com/blog/nginx-plus-r30-released/#Important-Changes-in-Behavior-

## Summary by CodeRabbit

- **New Features**
	- Enhanced SSL connection handling and HTTP/2 settings for improved performance and security.
	- Updated version to 3.11.1, reflecting the new nginx HTTP/2 directive.
- **Bug Fixes**
	- Streamlined configuration to ensure clarity and functionality of SSL and HTTP/2 settings.
	- Suppressed a deprecation warning related to HTTP/2 settings.

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
Looks good @RonnieDilli 👍 

However, please also bump the add-on version number and update the changelog. Once that is done, we can go ahead and merge this one in 👍 


../Frenck

**Review by RonnieDilli — COMMENTED** [review]
Uptate to new nginx http2 directive. This also supress a deprecation warning.
Bumped the addon version from 3.11.0 to 3.11.1 .

**Review by RonnieDilli — COMMENTED** [review]
Bumped the addon version from 3.11.0 to 3.11.1.
Also updated the changelog to: Update to new nginx http2 directive. This also suppress a deprecation warning.

Thanks @frenck, I'm glad to contribute.

**Review by frenck — APPROVED** [review]
Nice! Thanks, @RonnieDilli 👍 

../Frenck

**Pull request merged**
