### PR TITLE
Mosquitto and libwebsocket bump

### LINKED ISSUE #2904: Mosquitto: Unable to create websockets listener on port 1884
### Describe the issue you are experiencing

When I launch the mosquitto broker it complains about port 1884, even if I change the port in the configuration, the issue remains. So I think the port conflict should be inside the container.

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### Which add-on are you reporting an issue with?

Mosquitto broker

### What is the version of the add-on?

6.1.3

### Steps to reproduce the issue

1. Start  the addon with any configuration

## System Information

version | core-2023.3.1
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.10
os_name | Linux
os_version | 6.2.2-arch1-1
arch | x86_64
timezone | America/Sao_Paulo
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4962
Installed Version | 1.31.0
Stage | running
Available Repositories | 1242
Downloaded Repositories | 5

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Arch Linux
-- | --
update_channel | stable
supervisor_version | supervisor-2023.01.1
agent_version | 1.4.1
docker_version | 23.0.1
disk_total | 111.3 GB
disk_used | 50.5 GB
healthy | true
supported | failed to load: Unsupported
supervisor_api | ok
version_api | ok
installed_addons | Duck DNS (1.15.0), Home Assistant Google Drive Backup (0.110.1), Studio Code Server (5.5.3), Mosquitto broker (6.1.3), Terminal & SSH (9.6.1), SQLite Web (3.7.0), Zigbee2MQTT (1.30.2-1), Node-RED (14.0.3), NGINX Home Assistant SSL proxy (3.2.0), UniFi Network Application (2.5.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
views | 4
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 25 de fevereiro de 2023 às 19:43
-- | --
current_recorder_run | 6 de março de 2023 às 09:39
estimated_db_size | 356.35 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

<details><summary>Sonoff</summary>

version | 3.4.0 (5406fa7)
-- | --
cloud_online | 27 / 31
local_online | 27 / 27

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Anything in the Supervisor logs that might be useful for us?

```txt
23-03-06 09:43:13 INFO (SyncWorker_1) [supervisor.docker.interface] Cleaning addon_core_mosquitto application
23-03-06 09:43:13 INFO (SyncWorker_1) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-mosquitto with version 6.1.3
23-03-06 09:43:20 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Mosquitto broker is stopped, restarting...
23-03-06 09:43:20 INFO (SyncWorker_4) [supervisor.docker.interface] Cleaning addon_core_mosquitto application
23-03-06 09:43:21 INFO (SyncWorker_5) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-mosquitto with version 6.1.3
23-03-06 09:43:27 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Mosquitto broker is stopped, restarting...
23-03-06 09:43:27 INFO (SyncWorker_6) [supervisor.docker.interface] Cleaning addon_core_mosquitto application
23-03-06 09:43:27 INFO (SyncWorker_1) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-mosquitto with version 6.1.3
23-03-06 09:43:34 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Mosquitto broker is stopped, restarting...
23-03-06 09:43:34 INFO (SyncWorker_7) [supervisor.docker.interface] Cleaning addon_core_mosquitto application
23-03-06 09:43:34 INFO (SyncWorker_4) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-mosquitto with version 6.1.3
23-03-06 09:43:41 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Mosquitto broker is stopped, restarting...
23-03-06 09:43:41 INFO (SyncWorker_2) [supervisor.docker.interface] Cleaning addon_core_mosquitto application
23-03-06 09:43:41 INFO (SyncWorker_6) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-mosquitto with version 6.1.3
23-03-06 09:43:47 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Mosquitto broker is stopped, restarting...
23-03-06 09:43:47 INFO (SyncWorker_7) [supervisor.docker.interface] Cleaning addon_core_mosquitto application
23-03-06 09:43:48 INFO (SyncWorker_0) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-mosquitto with version 6.1.3
23-03-06 09:43:54 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Mosquitto broker is stopped, restarting...
23-03-06 09:43:54 INFO (SyncWorker_1) [supervisor.docker.interface] Cleaning addon_core_mosquitto application
23-03-06 09:43:55 INFO (SyncWorker_4) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-mosquitto with version 6.1.3
23-03-06 09:44:01 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Mosquitto broker is stopped, restarting...
23-03-06 09:44:01 INFO (SyncWorker_7) [supervisor.docker.interface] Cleaning addon_core_mosquitto application
23-03-06 09:44:01 INFO (SyncWorker_3) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-mosquitto with version 6.1.3
23-03-06 09:44:07 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Mosquitto broker is stopped, restarting...
```

### Anything in the add-on logs that might be useful for us?

```txt
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/mosquitto.sh
[09:29:48] INFO: Setting up user kodi
[09:29:48] INFO: Certificates found: SSL is available
cont-init: info: /etc/cont-init.d/mosquitto.sh exited 0
cont-init: info: running /etc/cont-init.d/nginx.sh
cont-init: info: /etc/cont-init.d/nginx.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun mosquitto (no readiness notification)
services-up: info: copying legacy longrun nginx (no readiness notification)
s6-rc: info: service legacy-services successfully started
[09:29:49] INFO: Starting NGINX for authentication handling...
[09:29:49] INFO: Starting mosquitto MQTT broker...
2023-03-06 09:29:49: Warning: Mosquitto should not be run as root/administrator.
2023-03-06 09:29:49: mosquitto version 2.0.11 starting
2023-03-06 09:29:49: Config loaded from /etc/mosquitto/mosquitto.conf.
2023-03-06 09:29:49: Loading plugin: /usr/share/mosquitto/go-auth.so
2023-03-06 09:29:49:  ├── Username/password checking enabled.
2023-03-06 09:29:49:  ├── TLS-PSK checking enabled.
2023-03-06 09:29:49:  └── Extended authentication not enabled.
2023-03-06 09:29:49: Opening ipv4 listen socket on port 1883.
2023-03-06 09:29:49: Opening ipv6 listen socket on port 1883.
2023-03-06 09:29:49: Opening websockets listen socket on port 1884.
2023-03-06 09:29:49: Error: Unable to create websockets listener on port 1884.
[12:29:49] WARNING: Halt add-on
s6-rc: info: service legacy-services: stopping
[12:29:49] INFO: Service restart after closing
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by rokam**
I believe that there is a fixed bug on libwebsocket that is already fixed on Debian bookworm.

I was also able to fix it using ubuntu base and adding the mosquitto ppa, but I think this is a better solution.

This fixes #2904

### CODE REVIEW

**Comment by rokam** [comment]
I was also able to fix it using ubuntu base and adding the mosquitto ppa, but I think this is a better solution.

**Comment by rokam** [comment]
> I don't think we should run bookworm in, what is supposed to be, a stable environment tbh.

Fair enough, so I'll change it to ubuntu with mosquitto ppa.

**Comment by rokam** [comment]
ppa will receive the last stable version of mosquitto and also some libs, including updated libwebsocket.
https://launchpad.net/~mosquitto-dev/+archive/ubuntu/mosquitto-ppa

The main issue is that we'll use ubuntu and there isn't a ubuntu base version for every arch already enabled to the addon.

The other way is to compile mosquitto and dependencies from scratch.

**Comment by rokam** [comment]
@frenck now I'm compiling it from scratch, works for me.

**Comment by spartandrew18** [comment]
I cannot use Mosquitto broker. When would this PR be merged?

**Comment by agners** [comment]
It seems that `lws_create_context()` fails for some reason. The version of libwebsockets used in Debian Bullseye is somewhat older (4.0.20). There is 4.0.21, but I wasn't able to find a change which might fix this.

Finding the exact bug is probably not worth it. Moving forward to the latest release seems sensible to me.

**Comment by agners** [comment]
@rokam  I've allowed myself to push some changes to your branch, hope that is fine!

I've tested test locally on HAOS 10.0.rc1 and things seem to work (add-on starts, I can connect, authenticate and publish MQTT messages).

**Review by agners — APPROVED** [review]

**Comment by LeChat109** [comment]
my question can be sttpid but how i apply the correction to my haos beta ?

**Comment by rokam** [comment]
> my question can seem stupid but how i apply the correction to my haos beta?

You can clone the repo and copy  mosquitto folder to `addons/local`.
And you also need to comment out the line: https://github.com/rokam/addons/blob/30be4415b1e0d47b1c9257212502a247c7ab6d7c/mosquitto/config.yaml#L17

**Comment by LeChat109** [comment]
ok thx

**Comment by spartandrew18** [comment]
> 

image

Is this correct? I cloned the repo and commented out the line but how do I go about installing it?

**Comment by spartandrew18** [comment]
> > my question can seem stupid but how i apply the correction to my haos beta?
> 
> 
> 
> You can clone the [repo](https://github.com/rokam/addons) and copy  mosquitto folder to `addons/local`.
> 
> And you also need to comment out the line: https://github.com/rokam/addons/blob/30be4415b1e0d47b1c9257212502a247c7ab6d7c/mosquitto/config.yaml#L17
> 
> 
> 
> The  installation will take some minutes

image

**Comment by rokam** [comment]
bashio is part of homeassistant debian base image. This error doesn't make any sense.

**Comment by spartandrew18** [comment]
> bashio is part of homeassistant debian base image. This error doesn't make any sense.

Idk that's what happened I couldn't run it at all. I had the files in there which made no sense to me. Any ideas?

**Comment by agners** [comment]
Also, just downgrade OS and be patient. It will get resolved at one point :smile:

**Comment by spartandrew18** [comment]
> 

Through samba share into the addons folder

**Comment by mdegat01** [comment]
Tested locally with and without websockets and everything checks out. Thanks @rokam and @agners !

**Comment by dodavies** [comment]
updating to OS 10 on HA blue and this error is still present

**Pull request merged**
