### PR TITLE
Hint to not use @ in password

### PR DESCRIPTION
**Pull request by gartenbauer**
A hint to not use @ in the mysql password, otherwise the connection does not work

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @gartenbauer, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;addons#2330).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Review by frenck — COMMENTED** [review]
Why wouldn't that work?

**Comment by gartenbauer** [comment]
The format to add recoder integration [db_url](https://www.home-assistant.io/integrations/recorder/#db_url)  for [mysql](https://www.home-assistant.io/integrations/recorder/#mysql) of is the fallowing: 
`mysql://user:password@SERVER_IP/DB_NAME?charset=utf8mb4`

When I chose a password with an @, the the logs of the homeassistant core gave me an error message.
I suspect the recorder is now trying to connect to the part in front of the @ with Mariadb. Which does not work, because on the one hand the password is wrong and on the other hand the IP makes no sense
**Example:**
password set in the mariadb addon: _CDhF@fp4%@j25&&#_
the recoder would try to connect to the server_ip: _j25&&#_

**Comment by frenck** [comment]
That is not because you can't, it's because you are using it incorrectly.

The database connection string is an URI; just like an URL,  which cannot contain `@` plain,  but they need to URL encoded. So, an `@` becomes: `%40`.

Closing this PR; as it is not correct.

**Pull request closed without merging**
