### PR TITLE
letsencrypt: Bump certbot-dns-directadmin to 1.0.12

### PR DESCRIPTION
**Pull request by 0xFelix**
Bump certbot-dns-directadmin to 1.0.12 in hope to fix issues with the support for pointer domains that was introduced in version 1.0.4.

## Summary by CodeRabbit

- **New Features**
	- Updated the `certbot-dns-directadmin` package to version 1.0.12 for improved DNS support.

- **Documentation**
	- Changelog updated to include new version entry for 5.2.5 with detailed changes.

- **Chores**
	- Incremented version number in configuration files to reflect the latest updates.

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
Hi there @0xFelix 👋 

It looks like the CI is failing. Can you take a look?

../Frenck

**Comment by 0xFelix** [comment]
Hi @frenck :wave: 

I'm looking at what I can do.

We're being blocked by https://github.com/cybercinch/certbot-dns-directadmin/issues/30 and https://github.com/cybercinch/certbot-dns-directadmin/issues/32.

**Review by sairon — COMMENTED** [review]
There's 1.0.10 on PyPI now, I'll leave it up to you if you'll prefer to update this PR or start with a new one

**Comment by 0xFelix** [comment]
@frenck @sairon Done, changed the version to `1.0.10`.

**Comment by 0xFelix** [comment]
CI is failing again. `certbot = "^3.0.1"` is to new.

See https://github.com/cybercinch/certbot-dns-directadmin/issues/32#issuecomment-2495630460

**Comment by guisea** [comment]
> CI is failing again. `certbot = "^3.0.1"` is too new.
> 
> See [cybercinch/certbot-dns-directadmin#32 (comment)](https://github.com/cybercinch/certbot-dns-directadmin/issues/32#issuecomment-2495630460)

Hey @0xFelix,  please note new package is uploaded.  I have loosened the version required as suggested.  New version is 1.0.12. 

Cheers

**Comment by 0xFelix** [comment]
@guisea Thank you again, very much appreciated.

**Review by agners — APPROVED** [review]
LGTM! Rebased on master which required the bump to 5.2.5.

**Review by sairon — APPROVED** [review]
Looks good, thanks everyone!

**Pull request merged**
