### PR TITLE
Adding support for DuckDNS challenge

### PR DESCRIPTION
**Pull request by miguelrjim**
Installing plugin for DuckDNS certbot challenge validation, tested it against my homeassistant instance by installing the addon locally.

### CODE REVIEW

**Comment by Zehir** [comment]
Any updates ?

**Review by mdegat01 — CHANGES_REQUESTED** [review]
So the PR looks good except you need to add an entry to the [changelog](https://github.com/home-assistant/addons/blob/master/letsencrypt/CHANGELOG.md).

Also in this particular case, can you explain why we need this? Because the [DuckDNS addon](https://github.com/home-assistant/addons/tree/master/duckdns) already exists. So this seems redundant?

**Comment by Zehir** [comment]
> So the PR looks good except you need to add an entry to the [changelog](https://github.com/home-assistant/addons/blob/master/letsencrypt/CHANGELOG.md).
> 
> Also in this particular case, can you explain why we need this? Because the [DuckDNS addon](https://github.com/home-assistant/addons/tree/master/duckdns) already exists. So this seems redundant?

Good point, I using the duckdns addon too

**Comment by miguelrjim** [comment]
> So the PR looks good except you need to add an entry to the [changelog](https://github.com/home-assistant/addons/blob/master/letsencrypt/CHANGELOG.md).
> 
> Also in this particular case, can you explain why we need this? Because the [DuckDNS addon](https://github.com/home-assistant/addons/tree/master/duckdns) already exists. So this seems redundant?

Mostly to give users a different way to manage their certificates; for reference, I'm using this [blueprint]( https://gist.github.com/mcnovy/caa97512ed7aedbe3f407bc7bbabe737) to manage renewal & restarting homeassistant to pick up the renewed certificate.

**Pull request closed without merging**
