### PR TITLE
Made git_pull more robust to wrong repo setup and added failsafe backup

### PR DESCRIPTION
**Pull request by ladidadida**
This patch is to solve issue #1690 and similar.
The problem is, that especially in the beginning it is very likely to run into problems, but without checking quality of remote Repo, all data is deleted.
This patch tries to solve this, but not only create backups far more often, but because it reverts configuration in case of bigger problems.

A second, small change is, to not delete the whole config folder, but to just delete yaml files from it. If additional files should be deleted, this could be achieved with git, too. (add a file to repo once and then delete it from repo). I would assume that only pulling updates from Repo is sufficient, but this is not yet implemented.

### CODE REVIEW

**Review by pvizeli — COMMENTED** [review]
Please use bashio for logging and exit

**Comment by ladidadida** [comment]
@pvizeli 
> Please use bashio for logging and exit
Should I do that only for my changed parts or for the whole file?
I have tried to use bashio for getting the configuration items, but it seems this does not work that easy. I would have to dig more into the bashio functionality.

Is there any documentation for bashio?

**Comment by pvizeli** [comment]
https://github.com/hassio-addons/bashio

**Comment by ladidadida** [comment]
> https://github.com/hassio-addons/bashio

Short answer with zero new information ;) The package lacks documentation. Ok, some might now say good code is documentation enough, but I am not one of those. I digged into it and found that it should not differ. I will have to dig deeper into my changes.

**Pull request closed without merging**
