### PR TITLE
zwave: Remove old OpenZWave add-on

### PR DESCRIPTION
**Pull request by frenck**
This PR suggests removing the OpenZWave add-on. 

The OpenZWave integration has been deprecated for a long time and removed from Home Assistant a couple of releases ago.

### CODE REVIEW

**Comment by MartinHjelmare** [comment]
How does this work for users running an old core version still using the ozw integration with this add-on?

**Comment by frenck** [comment]
The current installation will just keep working (the add-ons do not stop or get un-installed or something).

**Comment by MartinHjelmare** [comment]
Will the user be able to install the add-on on a new host?

**Comment by MartinHjelmare** [comment]
I think we should wait a year after we removed the ozw integration before removing the add-on.

**Pull request closed without merging**
