### PR TITLE
Bump config check base to `2022.05.0`

### LINKED ISSUE #2512: Upgrade from 2022.5.5 to 2022.6: check_config add-on reports error with python
### Describe the issue you are experiencing

I'm following up on https://github.com/home-assistant/core/issues/72868, where allenporter asked that I create a separate issue.

When running the Check Home Assistant configuration add-on for the latest version (2022.6), the following error occured and displayed in the log:

`Testing configuration at /tmp/config Failed config General Errors: - Component error: nest - Error relocating /usr/local/lib/python3.9/site-packages/grpc/_cython/cygrpc.cpython-39-arm-linux-gnueabihf.so: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7reserveEv: symbol not found`

Please note that after reviewing documentation and checking my backups, I decided to upgrade to 2022.6, and that worked without any issues.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Check Home Assistant configuration

### What is the version of the add-on?

3.10.0

### Steps to reproduce the issue

1. Start the Check Home Assistant configuration add-on
2. Wait for it to install a new version
3. Check the log for details. It fails with the error I reported above.

### Anything in the Supervisor logs that might be useful for us?

```txt
N/A
```

### Anything in the add-on logs that might be useful for us?

```txt
N/A
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by mdegat01**
Bump config check base from `2022.02.0` to `2022.05.0` to match core

Fixes #2512

### CODE REVIEW

**Review by frenck — APPROVED** [review]
✅ 

We should consider deprecating this add-on IMHO. It doesn't hold its original value anymore (it originates from the time that upgrading with a configuration breaking change would cause your system not to come up again, which is no longer the case).

**Comment by mdegat01** [comment]
@frenck idk I mean I still find the idea of it pretty useful personally? It would be nice to know before you updated and wound up in emergency mode that something is wrong about your config. Although its useful does depend on how many yaml-configurable integrations you have since it does nothing for UI-configurable ones

**Comment by frenck** [comment]
> It would be nice to know before you updated and wound up in emergency mode that something is wrong about your config.

That is the whole point, updating won't trigger that.

**Comment by ludeeus** [comment]
Since we are not testing the configuration against the same container image as what you get when you are upgrading, this add-on has really never been that much help and have always caused confusion and false results.
I'm in favor of deprecating it.

If things go bad, the supervisor will do a rollback.

**Pull request merged**
