### PR TITLE
Bump deCONZ to v2.24.2

### PR DESCRIPTION
**Pull request by beginnersguide**
Update to the latest stable deconz release [v2.24.2](https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/v2.24.2)

### CODE REVIEW

**Comment by frenck** [comment]
Marking this PR draft awaiting the above question. Additionally, the CI failed as well. Could you take a look @beginnersguide?

Thanks! 👍 

../Frenck

**Comment by jasperslits** [comment]
CI fails because the the .deb files on Dresden's server is deconz-2.24.2-qt5.deb and build.yaml specifies 2.24.**02** 

https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/v2.23.2 fixes the bug that caused the revert.

**Comment by beginnersguide** [comment]
@frenck sorry for the late reply. Like @jasperslits alreafdy said, the bug is fixed.

**Comment by beginnersguide** [comment]
> > How did you test this?
> 
> Right, but how did you test this?
> 
> ../Frenck

Personally, I have not tested it.

https://forum.phoscon.de/t/phoscon-de-pwa-login-html-does-not-work-anymore/3967/73

**Comment by frenck** [comment]
> Personally, I have not tested it.

Sorry, but I hope you understand that we cannot accept a PR and roll it out to users without testing.

**Comment by pimw1** [comment]
Hi, if someone can explain me how i  can install this via home assistant os, rpi4, i can test.

**Comment by matata86** [comment]
Any news please?

**Comment by francescopeloi** [comment]
> Hi, if someone can explain me how i can install this via home assistant os, rpi4, i can test.

https://developers.home-assistant.io/docs/add-ons/testing

**Comment by jasperslits** [comment]
I took a bit of a different approach. There are probably smarter ways but it did the job:
1) Install current add-on via HA and plug deCONZ stick in and start it
2) Build Docker image locally using 2.24.2 and reference it in addons.json
`docker buildx build --build-arg BUILD_FROM=ghcr.io/home-assistant/amd64-base-debian:buster --build-arg BUILD_ARCH=amd64 --build-arg DECONZ_VERSION=2.24.2 .`
3) Restart add-on
4) Open using add-on 'Open Web UI' and confirm Phoscon + deCONZ buttons work
5) Open deCONZ using left menu and confirm Phoscon + deCONZ buttons work

https://forum.phoscon.de/t/phoscon-de-pwa-login-html-does-not-work-anymore/3967/73 also has a confirmation from another user that it works. 

(Unrelated: I tried also to build with bookworm but that caused problems as wmii package was not present. When removing it from the Docker file the resulting image / container started but failed because of vnc problems. I'll look into that but that's for another PR if I get it to work)

**Comment by francescopeloi** [comment]
> I took a bit of a different approach. There are probably smarter ways but it did the job:
> 
> 1. Install current add-on via HA and plug deCONZ stick in and start it
> 2. Build Docker image locally using 2.24.2 and reference it in addons.json
>    `docker buildx build --build-arg BUILD_FROM=ghcr.io/home-assistant/amd64-base-debian:buster --build-arg BUILD_ARCH=amd64 --build-arg DECONZ_VERSION=2.24.2 .`
> 3. Restart add-on
> 4. Open using add-on 'Open Web UI' and confirm Phoscon + deCONZ buttons work
> 5. Open deCONZ using left menu and confirm Phoscon + deCONZ buttons work
> 
> https://forum.phoscon.de/t/phoscon-de-pwa-login-html-does-not-work-anymore/3967/73 also has a confirmation from another user that it works.
> 
> (Unrelated: I tried also to build with bookworm but that caused problems as wmii package was not present. When removing it from the Docker file the resulting image / container started but failed because of vnc problems. I'll look into that but that's for another PR if I get it to work)

where is the `addons.json` file you are mentioning?

**Comment by Pirionfr** [comment]
First someone need to merge it.
After that it will be availlable rapidly.

**Comment by phwagner82** [comment]
what is here the last status in this case?

**Comment by bcutter** [comment]
> > Personally, I have not tested it.
> 
> 
> 
> Sorry, but I hope you understand that we cannot accept a PR and roll it out to users without testing. 

frenck: are the positive testing reports starting with https://github.com/home-assistant/addons/pull/3323#issuecomment-1831752175 enough/fine for you to merge this?

**Comment by jaytea33** [comment]
Can we get some attention on this issue? Seems silly to fork it just to get it up to the latest only to switch again once it's implemented.

This add-on is very widely used and I thought for sure it'd be in the last couple HA updates.

**Comment by beginnersguide** [comment]
> Can we get some attention on this issue? Seems silly to fork it just to get it up to the latest only to switch again once it's implemented.
> 
> This add-on is very widely used and I thought for sure it'd be in the last couple HA updates.

The bug is solved and someone has successfully tested the new release. 

If a bunch of people have to test things before it's implemented, I'm asking how it's possible that there are currently problems regarding the matter server.

**Comment by eduardofilipe3** [comment]
Any news on this topic? It would be really nice to have this version deployed.
@frenck maybe you can help us

**Comment by frenck** [comment]
I've closed the unrelated comments. Please let's keep PRs aimed at reviews.

As for this PR, the way it was tested is not the correct way. Our developer documentation can be found on our developer portal at https://developers.home-assistant.io

I'm currently trying to build this PR locally against a few machines and test it against a conbee 1 & 2.

../Frenck

**Comment by frenck** [comment]
Small update: The build on the Blue/N2 took an unusual amount of time (to the point the Supervisor even bailed out). Looking into why that happens.

**Comment by frenck** [comment]
Did some testing, most seems to work, but the gateway page doesn't.

CleanShot 2023-12-14 at 08 53 34@2x

**Comment by Drumdevil** [comment]
> Did some testing, most seems to work, but the gateway page doesn't.


Are those whitespaces?

whitespaces

**Comment by frenck** [comment]
> Are those whitespaces?

No underscores, however, these are side-effects of the actual issue right now. Not sure what is going on. I'm going to collect some information, try some things and reach out to dresden.

../Frenck

**Comment by ChrisHae** [comment]
@frenck You said other pages are working? Could you share a screenshot with console output from one of the sites?

**Comment by frenck** [comment]
> You said other pages are working?

Sort of yes, but have similar errors in the console.

> is 8123 the correct port for opening the Phoscon App ?

It is ingress, so: Yes.

**Comment by ChrisHae** [comment]
Could you share a console screenshot of another site?

**Comment by frenck** [comment]
See other screenshot above, as said, it shows the same errors.

**Comment by egnerfl** [comment]
@frenck could the issues on the gateway settings page be related to this issue?

https://github.com/home-assistant/addons/issues/3334

**Comment by frenck** [comment]
@egnerfl No, that is not related.

**Comment by ChrisHae** [comment]
@frenck Can you show me the Request of the index.html in the Network tab of chrome?
image

**Comment by egnerfl** [comment]
I just found this [tweet](https://twitter.com/phosconde/status/1726641343525752929) and a custom[ deconz-beta addon ](https://github.com/wovka88/hassio-addons/tree/main/deconz-beta)which works just fine (tested it myself, gateway page and all devices look good).

Is there any update on this PR? 
Otherwise the deconz developers or the developer behind the beta addon @wovka88 might be able to help?

**Comment by roelvandermade** [comment]
> I just found this [tweet](https://twitter.com/phosconde/status/1726641343525752929) and a custom[ deconz-beta addon ](https://github.com/wovka88/hassio-addons/tree/main/deconz-beta)which works just fine (tested it myself, gateway page and all devices look good).
> 
> Is there any update on this PR? Otherwise the deconz developers or the developer behind the beta addon @wovka88 might be able to help?

Yeah well, not really..  tried running the beta from your mentioned repository but it has issues starting up (and probably thus cannot see the Phoscon or deCONZ VNC screens):

```
[10:36:27] INFO: Starting VNC server (local/yes)...
if: fatal: unable to spawn s6-test: No such file or directory
[10:36:29] INFO: Starting VNC server (local/yes)...
if: fatal: unable to spawn s6-test: No such file or directory
[10:36:30] INFO: Starting VNC server (local/yes)...
if: fatal: unable to spawn s6-test: No such file or directory
```

Am running HA 2023.12.4, and don't get me wrong, am VERY much waiting for the conbee-iii supported version to arrive in a stable manner :)

**Comment by egnerfl** [comment]
> > I just found this [tweet](https://twitter.com/phosconde/status/1726641343525752929) and a custom[ deconz-beta addon ](https://github.com/wovka88/hassio-addons/tree/main/deconz-beta)which works just fine (tested it myself, gateway page and all devices look good).
> > Is there any update on this PR? Otherwise the deconz developers or the developer behind the beta addon @wovka88 might be able to help?
> 
> Yeah well, not really.. tried running the beta from your mentioned repository but it has issues starting up (and probably thus cannot see the Phoscon or deCONZ VNC screens):
> 
> ```
> [10:36:27] INFO: Starting VNC server (local/yes)...
> if: fatal: unable to spawn s6-test: No such file or directory
> [10:36:29] INFO: Starting VNC server (local/yes)...
> if: fatal: unable to spawn s6-test: No such file or directory
> [10:36:30] INFO: Starting VNC server (local/yes)...
> if: fatal: unable to spawn s6-test: No such file or directory
> ```
> 
> Am running HA 2023.12.4, and don't get me wrong, am VERY much waiting for the conbee-iii supported version to arrive in a stable manner :)

I just plugged in the Conbee 3 and it works like a charm. Just had to restart the addon after uploading my Conbee 2 Backup. 
VNC works fine and I don't see the "Starting VNC server" message in the addon log.

Screenshot 2023-12-28 at 10 44 18

**Comment by roelvandermade** [comment]
> > > I just found this [tweet](https://twitter.com/phosconde/status/1726641343525752929) and a custom[ deconz-beta addon ](https://github.com/wovka88/hassio-addons/tree/main/deconz-beta)which works just fine (tested it myself, gateway page and all devices look good).
> > > Is there any update on this PR? Otherwise the deconz developers or the developer behind the beta addon @wovka88 might be able to help?
> > 
> > 
> > Yeah well, not really.. tried running the beta from your mentioned repository but it has issues starting up (and probably thus cannot see the Phoscon or deCONZ VNC screens):
> > ```
> > [10:36:27] INFO: Starting VNC server (local/yes)...
> > if: fatal: unable to spawn s6-test: No such file or directory
> > [10:36:29] INFO: Starting VNC server (local/yes)...
> > if: fatal: unable to spawn s6-test: No such file or directory
> > [10:36:30] INFO: Starting VNC server (local/yes)...
> > if: fatal: unable to spawn s6-test: No such file or directory
> > ```
> > Am running HA 2023.12.4, and don't get me wrong, am VERY much waiting for the conbee-iii supported version to arrive in a stable manner :)
> 
> I just plugged in the Conbee 3 and it works like a charm. Just had to restart the addon after uploading my Conbee 2 Backup. VNC works fine and I don't see the "Starting VNC server" message in the addon log.

Ok, so this is interesting, after restarting HA, stopping decONZ 6.22.0 and starting deCONZ v2.25.0-r0 (from the repo above) it DOES work fine indeed.  I will be running this now for a little while to see if I encounter any issues, will report back if I do.

**Comment by francescopeloi** [comment]
> I just found this [tweet](https://twitter.com/phosconde/status/1726641343525752929)

I don't get why deconz advertises to its users that the upgrade is going to happen soon, when they are not in control of it AND the last upgrade has gone horrendously wrong. More than a month later we are at page 1.

**Comment by wovka88** [comment]
> Did some testing, most seems to work, but the gateway page doesn't.
> 
> CleanShot 2023-12-14 at 08 53 34@2x
> 
> For completeness, on this device and my browser, this cannot be a caching issue in this case. There are more pages throwing errors.
> 
> This might be related to:
> 
> CleanShot 2023-12-14 at 08 56 37@2x
> 
> Which is odd, as that updater should only run once every 259200 seconds. This indicates this process is crashing as well, causing endless attempts.
> 
> Edit: Seems like the `deCONZ-otau-dl.sh` file no longer exists in the deCONZ package...

The script name changed from `deCONZ-otau-dl.sh` to `deCONZ-ikea-ota-download.sh`
https://github.com/wovka88/hassio-addons/blob/main/deconz-beta/rootfs/etc/services.d/otau-deconz/run

**Comment by wovka88** [comment]
> I just found this [tweet](https://twitter.com/phosconde/status/1726641343525752929) and a custom[ deconz-beta addon ](https://github.com/wovka88/hassio-addons/tree/main/deconz-beta)which works just fine (tested it myself, gateway page and all devices look good).
> 
> Is there any update on this PR? Otherwise the deconz developers or the developer behind the beta addon @wovka88 might be able to help?

I would be happy if we could publish my update here.

I have been running the version for several months now and have made the following adjustments so far:
- Update to Debian Bookworm
- Switched from WMII to Openbox (because I was missing the close button)
- added healthcheck

Someone would just need to assist support to run all the necessary tests for @frenck to approve the update.

**Comment by frenck** [comment]
> The script name changed from `deCONZ-otau-dl.sh` to `deCONZ-ikea-ota-download.sh`

That isn't correct. Those are not the same things.

**Comment by wovka88** [comment]
> > The script name changed from `deCONZ-otau-dl.sh` to `deCONZ-ikea-ota-download.sh`
> 
> That isn't correct. Those are not the same things.

true, the other scripts downloads from https://deconz.dresden-elektronik.de/otau/

**Comment by Der-WU** [comment]
How can i Test The Version from Wovka88?

greatz

**Comment by mirml** [comment]
It is moving 

https://forum.phoscon.de/t/phoscon-de-pwa-login-html-does-not-work-anymore/3967/81

Screenshot_20231230_151749_Brave

**Comment by steljwagh** [comment]
December is a pretty busy month, let's try to get this resolved in januari. Meanwhile I moved my installation completely away from home assistant due to missing out on all the upates (also needed for devices).
I'm now running a separate (standalone) docker instance and connected home assistant to that instance.

**Comment by steljwagh** [comment]
> I am also moving away from the HA addon, and installed deCONZ on a separate SOC instead.
> 
> I noticed while reviewing the official install instructions for the Conbee III, that Phoscon themselves are seemingly hinting that you should use [ZHA in Home Assistant](https://phoscon.de/en/conbee3/install#hazha). This is new to me, and the Conbee II doesn't have this instruction.

While I don't like phoscon, I do like the deconz application user interface for configuring, troubleshooting, insight, tweaking and modifying ddf's. I don't see those possibilities with ZHA. You do see the discovered add-on whenever you present a Conbee II to HA nowadays, but I don't like it. Not enough options, no visiblity, not anything mentioned above, sorry guys.

**Comment by Drumdevil** [comment]
> While I don't like phoscon, I do like the deconz application user interface for configuring, troubleshooting, insight, tweaking and modifying ddf's. I don't see those possibilities with ZHA. You do see the discovered add-on ZHA (so not deconz?) whenever you present a Conbee II to HA nowadays, but I don't like it. Not enough options, no visibility, not anything mentioned above, sorry guys.


I guess the instructions are mainly aimed towards cases where one wants a flat, reliable and consolidated home automation system, which is ZHA's purpose.

**Comment by dutch-erik** [comment]
Are issues the reason why add-on version: 6.23.0 (DECONZ_VERSION: 2.24.2) is not released yet?
Can you give some insights?

**Comment by phwagner82** [comment]
I want to say that it is annoying to have to wait so long for this update. It doesn't reflect well on Homeassistant and DECONZ. Many users were waiting for this update and no one understands the real problem. Please be behind to solve this problem as soon as possible and release the update.

**Comment by Drumdevil** [comment]
Since I had bought the Conbee III and already had a couple of Rodrets laying around for months, I got tired of waiting, and switched to the latest non-ingress of deCONZ using a Raspi 4. 

I am certainly no expert, but I've been an tech/IT guy pretty much my whole life, and got 4 years of experience with an ever expanding Zigbee network and all of it's subsequent challenges.  Was doing everything by the book, but I encountered so many issues regarding pairing, overal stability and insane battery drain on all IKEA remotes. I even started from scratch on an Odroid N2 to rule out the Raspi 4, Had both devices at various locations inside the home, replaced the USB 2 extension cable with a brand new shielded one, upgraded Conbee III firmware, wrote a script that checks WiFi channel saturation as well as sniffs Zigbee packets to check for existing networks, and tried 3 different channels. Nothing helped; the network remained unstable. 

After nearly a week of messing around, several packages of different A-brand CR2032 batteries, and then still finding stuff broken overnight... I just gave up. I switched to ZHA, and it's been a day and night difference. Or more literally: A light on and off difference. Everything worked instantly. Still had the battery drain issue, and that was eventually solved with downgrading the Conbee III firmware. 

To me personally, deCONZ support has been less than helpful, and I think their priority doesn't really lie with assisting the HA addon to work.

**Comment by ChrisHae** [comment]
We have installed our own ZHA Addon developer environment and found the solution for these problems. So the next deconz stable version 2.24.3 can be put in ZHA deCONZ Addon.

**Comment by steljwagh** [comment]
I'm kind of disappointed in the lack of attention from Phoscon. I especially bought the conbeeII stick to never have to worry about support. Zigbee2mqtt users are now laughing. ;)
All jokes aside, I hope there will be an update soon and the people with Phoscon have some proper CI/CD pipeline implementation.

**Comment by jasperslits** [comment]
https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/v2.24.3 is released with "Fix Phoscon App Home Assistent add-on login and Ingress support." as highlight.

**Comment by mirml** [comment]
Excelent 👍

**Comment by francescopeloi** [comment]
I was curious regarding what the problem was, so I went and looked at all the commits for this new version. I couldn't find any commit description describing a fix for Phoscon/HA addon. Looked at the files changed and felt the same. Looked all the changes and again felt the same. Might be my ignorance, but this is confusing.

**Comment by dutch-erik** [comment]
> I was curious regarding what the problem was, so I went and looked at all the commits for this new version. I couldn't find any commit description describing a fix for Phoscon/HA addon. Looked at the files changed and felt the same. Looked all the changes and again felt the same. Might be my ignorance, but this is confusing.

Hopefully @frenck can give us some insights. ;)

**Comment by jasperslits** [comment]
> I was curious regarding what the problem was, so I went and looked at all the commits for this new version. I couldn't find any commit description describing a fix for Phoscon/HA addon. Looked at the files changed and felt the same. Looked all the changes and again felt the same. Might be my ignorance, but this is confusing.

That's because not all files used are in the Dresden Eletroknik github repo like all content under /usr/share/deCONZ/webapp such as login.html but they're part of the .deb package

**Comment by francescopeloi** [comment]
I see, thanks @jasperslits . Do you know where these are? I can't find a public repo within their org with these files.

**Comment by jasperslits** [comment]
No idea, you need to ask the developers

> I see, thanks @jasperslits . Do you know where these are? I can't find a public repo within their org with these files.

No idea. It's probably better to ask this on the Phoscon / Dresden Elektronik channels like https://forum.phoscon.de

**Comment by ChrisHae** [comment]
Hi. Indeed the problem was fixed within the Phoscon app. The Phoscon app is not open source and just packed with the deCONZ releases thats why there is no information at the deCONZ / Rest API plugin repository.

**Comment by dutch-erik** [comment]
I'm curious about the status of the add-on's update. 
"This pull request is still a work in progress"
It's so quite from HA side... is there any progress at all at the moment?

**Comment by bcutter** [comment]
So guys... what's missing? 5 months for a regular minor release update is quite... "extensive".

**Comment by mirml** [comment]
Indeed.

**Comment by bcutter** [comment]
Continue @

https://github.com/home-assistant/addons/pull/3432

**Comment by phwagner82** [comment]
no update, no news... nothing.... it is really annoying

**Comment by frenck** [comment]
Superseded by #3432

**Pull request closed without merging**
