### PR TITLE
Bump zwave-js to 12.1.1

### PR DESCRIPTION
**Pull request by raman325**
Mostly config file changes although a bug fix for multi-target firmware updates which has been an issue for a while

- [Z-Wave JS 12.1.0](https://github.com/zwave-js/node-zwave-js/releases/tag/v12.1.0)
- [Z-Wave JS 12.1.1](https://github.com/zwave-js/node-zwave-js/releases/tag/v12.1.1)

CC @AlCalzone

### CODE REVIEW

**Review by MartinHjelmare — APPROVED** [review]

**Comment by AlCalzone** [comment]
Should we make sure the repair issues are skippable before merging this?

**Comment by raman325** [comment]
they are confirmed not skippable if there is a repair flow. We can hold off on updating the add-on, however keep in mind that `zwave-js-ui` users are already seeing this.

**Comment by AlCalzone** [comment]
I don't mind either way. Is the repair clear enough for users to understand that they don't have to do it?

**Comment by raman325** [comment]
Yes. I'd suggest we merge if the firmware update issue is a big problem. Does it cause devices to brick?

**Comment by raman325** [comment]
I'm going to go ahead and merge so that people can get the benefits of the config file updates and the firmware update fixes. There are enough users on zwave-js-ui that have not complained about that particular annoyance so I think it's ok to push forward.

**Comment by AlCalzone** [comment]
The problematic firmware updates are disabled and will stay so until the driver version with the fix has significant usage.

**Pull request merged**
