### PR TITLE
vlc: Fix race condition at startup

### PR DESCRIPTION
**Pull request by agners**
Fixes: https://github.com/home-assistant/addons/issues/3186#issuecomment-1868098475

### CODE REVIEW

**Review by frenck — APPROVED** [review]
Thanks, @agners 👍 

../Frenck

**Comment by upsuper** [comment]
@agners Thanks for fixing it.

Out of curiosity, could you explain a bit how this would fix the race condition of creating the secret? It seems to me the only change in this PR is adding an empty `base` file, which isn't very obvious how it can affect the execution order between secret reading and writing.

**Comment by frenck** [comment]
It ensures the base of the S6-Overlay runs first (which should always be set up first).
The empty file denotes a dependency.

**Comment by upsuper** [comment]
I see. Thanks for explaining!

**Pull request merged**
