### PR TITLE
Bump zwave-js-server to 1.5.0 and zwave-js to 7.2.4

### PR DESCRIPTION
**Pull request by raman325**
zwave-js changelog: https://github.com/zwave-js/node-zwave-js/releases/tag/v7.2.4
zwave-js-server changelog: https://github.com/zwave-js/zwave-js-server/releases/tag/1.5.0

### CODE REVIEW

**Comment by raman325** [comment]
No idea why shell check is failing on this

**Review by frenck — APPROVED** [review]
Thanks, @raman325 👍 

The shellcheck error is indeed not related. Feel free to merge when ready to ship 👍 

../Frenck 🚂

**Comment by raman325** [comment]
this is ready to ship @frenck but I don't have merge rights 🙂 , can you merge?

**Comment by frenck** [comment]
Done!

**Pull request merged**
