### PR TITLE
🐛 Fix problems with alias domains and dns-01 challenge

### LINKED ISSUE #1331: DuckDNS Alias domain fails dns-01 challenge
When trying the new alias option in DuckDNS addon-on, the following gets generated (redacted is a placeholder name for a real domain I use, <SNIP> is personally identifiable data I have redacted):

```
# INFO: Using main config file /data/workdir/config
Processing redacted.duckdns.org with alternative names: home.redacted.net
 + Checking domain name(s) of existing cert... changed!
 + Domain name(s) are not matching!
 + Names in old certificate: redacted.duckdns.org
 + Configured names: redacted.duckdns.org home.redacted.net
 + Forcing renew.
 + Checking expire date of existing cert...
 + Valid till Aug 18 09:02:44 2020 GMT Certificate will not expire
(Longer than 30 days). Ignoring because renew was forced!
 + Signing domains...
 + Generating private key...
 + Generating signing request...
 + Requesting new certificate order from CA...
 + Received 2 authorizations URLs from the CA
 + Handling authorization for redacted.duckdns.org
 + Found valid authorization for redacted.duckdns.org
 + Handling authorization for home.redacted.net
 + 1 pending challenge(s)
 + Deploying challenge tokens...
OK + Responding to challenge for home.redacted.net authorization...
 + Cleaning challenge tokens...
OK + Challenge validation has failed :(
ERROR: Challenge is invalid! (returned: invalid) (result: {
  "type": "dns-01",
  "status": "invalid",
  "error": {
    "type": "urn:ietf:params:acme:error:dns",
    "detail": "DNS problem: NXDOMAIN looking up TXT for _acme-challenge.home.redacted.net - check that a DNS record exists for this domain",
    "status": 400
  },
  "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/<SNIP>/<SNIP>",
  "token": "<SNIP>"
})
```

I have added the following CNAME record to my redacted.net domain:

**home   >>  redacted.duckdns.org**

The configuration I am using is as follows:
```
lets_encrypt:
  accept_terms: true
  certfile: fullchain.pem
  keyfile: privkey.pem
token: <SNIP>
domains:
  - redacted.duckdns.org
  - home.redacted.net
aliases:
  - domain: home.redacted.net
    alias: redacted.duckdns.org
seconds: 300
```

### PR DESCRIPTION
**Pull request by RyanMeulenkamp**
And add some documentation to clarify a bit.

Resolves #1331

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @RyanMeulenkamp, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;addons#1785).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Review by pvizeli — COMMENTED** [review]
Please bump version and update the changelog

**Comment by pvizeli** [comment]
@RyanMeulenkamp please look at my comment, after that we can merge it 👍

**Review by pvizeli — APPROVED** [review]

**Comment by matlimatli** [comment]
@RyanMeulenkamp Have you seen  #1869 ? It seems like some people (myself included) have trouble obtaining certs after this change was merged.

**Comment by Xebozone** [comment]
@RyanMeulenkamp @pvizeli 
Are we sure this is resolved? Myself and others still continue to have issues.
See on the comments on:
https://github.com/home-assistant/addons/issues/1331

**Pull request merged**
