### PR TITLE
deCONZ 2.13.4 (stable)

### LINKED ISSUE #2313: Update to deCONZ 2.13.4 in order to make IKEA updated firmware work again
### Describe the issue you are experiencing

Please Update the add-on to deCONZ 2.13.4 in order to make IKEA updated firmware work again

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

deCONZ

### What is the version of the add-on?

 6.10.0

### Steps to reproduce the issue

1.
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

_No response_

### Anything in the add-on logs that might be useful for us?

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by fi-sch**
Bump deCONZ version to 2.13.04

fixes #2313

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @fi-sch, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;addons#2312).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by frenck** [comment]
Seems like there is an issue with the aarch64 build of deConz. Did you actually test this before making the PR?

**Comment by fi-sch** [comment]
> Seems like there is an issue with the aarch64 build of deConz. Did you actually test this before making the PR?

Nope. I admit that I did not test this version of deCONZ yet.

**Comment by frenck** [comment]
> Nope. I admit that I did not test this version of deCONZ yet.

I would strongly recommend you not to do drive-by PRs (as what these types of PRs are called). That is really not helpful for anybody.

Can you please look into the build issue?

**Comment by fi-sch** [comment]
> > Nope. I admit that I did not test this version of deCONZ yet.
> 
> I would strongly recommend you not to do drive-by PRs (as what these types of PRs are called). That is really not helpful for anybody.
> 
> Can you please look into the build issue?

I am deeply sorry. I just did not wanted to disturb you with feature request to bump deCONZ, and tried to suggest changes by myself. This won't happen in the future.
For me, it looks like they changed minimum required Debian version to Buster.

http://deconz.dresden-elektronik.de/debian/stable/

**Comment by Warter21** [comment]
The aarch64 link points to the old stretch version but it is not exist for the new version. It is buster related.
http://deconz.dresden-elektronik.de/debian/stable/deconz_2.13.04-debian-buster-stable_arm64.deb

**Comment by pvizeli** [comment]
Maybe we should go with bullseye?

**Comment by fi-sch** [comment]
Ok, at this point I can admit that it overwhelmed me. Should I just close this PR?

**Review by pvizeli — APPROVED** [review]

**Review by frenck — APPROVED** [review]

**Pull request merged**
