### PR TITLE
Apple Device Support

### PR DESCRIPTION
**Pull request by ananthb**
Load vfs_fruit modules for better Apple device support.

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @ananthb, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;addons#2268).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by tomkv** [comment]
Sorry to enter into this conversation with this, but Local Master should not be used.

Local Master is part of SMB1, which is obsolete and security risk. Microsoft has recommended not to use SMB1 for years (https://techcommunity.microsoft.com/t5/storage-at-microsoft/stop-using-smb1/ba-p/425858), and Windows 10 disables SMB1 support, if not used in few days after installation.

For modern discovery, other protocols are being used: WSD for Windows and Zeroconf/Bonjour for macOS and Linux. Samba itself doesn't implement WSD, but there is a third-party project that does (https://github.com/christgau/wsdd). Zeroconf/Bonjour is implemented by Avahi.

For a supported, future-proof discovery methods, I would suggest to implement these protocols, instead of enabling legacy one.

**Comment by ananthb** [comment]
@tomkv I had no idea that was deprecated. I'll remove that and leave the fruit stuff in because it looks nicer on Macs. Would you be interested in me adding Zeroconf and WSD to samba? I'd like to tackle that.

**Comment by tomkv** [comment]
@ananthb implementing WSD for Samba is another can of worms... see https://bugzilla.samba.org/show_bug.cgi?id=11473. I would suggest integrating the above mentioned wsdd instead. It would be also much easier ;). Synology also went this route (for wsd, they use their own solution, `synowsdiscoveryd`, but the same principle; for Zeroconf, they use Avahi with a simple config file - it basically advertises _smb._tcp service at port 445).

**Comment by ananthb** [comment]
@tomkv I've left just the vfs_fruit changes here. I'll raise another PR for the discovery stuff once I dig into WSD a bit more.

**Pull request closed without merging**
