### PR TITLE
Bump Z-Wave JS to 7.11.0

### PR DESCRIPTION
**Pull request by Aohzan**
Bump Z-Wave JS to 7.11.0

### CODE REVIEW

**Comment by MartinHjelmare** [comment]
Thanks for the PR! Did you test the updated add-on locally?

**Comment by Aohzan** [comment]
> Thanks for the PR! Did you test the updated add-on locally?

No I don't even know how to do it :sweat_smile:

**Comment by MartinHjelmare** [comment]
Here's the docs how to build the add-on locally:
https://developers.home-assistant.io/docs/add-ons/testing#remote-development

**Comment by Aohzan** [comment]
I successfully created the image, but I can't run it properly
`docker run --rm -v /usr/share/hassio/addons/data/core_zwave_js:/data:rw -v /dev:/dev:ro -p 3000:3000  --device=/dev/ttyACM0 local/zwavetest:latest "/init"`
```
Error parsing config file 0x5254/zdm-80s.json: ENOENT: no such file or directo
                                  ry, uv_cwd
...
2021-07-11T21:37:35.800Z CNTRLR   All nodes are ready to be used
...
2021-07-11T21:37:37.788Z DRIVER   Serial port errored: Error Resource temporarily unavailable Cannot lock port
Unable to start driver [Error: Error Resource temporarily unavailable Cannot lock port]
curl: (7) Failed to connect to supervisor port 80: Connection refused
```

**Comment by MartinHjelmare** [comment]
I have only tested building and running the add-on on a real instance of Home Assistant. That normally works.

**Comment by Aohzan** [comment]
Yes this part works

**Pull request closed without merging**
