### PR TITLE
dnsmasq: extend the default dns servers to more than ipv4-only google

### PR DESCRIPTION
**Pull request by RubenKelevra**
Currently, the default DNS servers are only two ipv4 addresses from Google.

This PR extends this list to more providers which all support dnssec and do no filtering.

[Source](https://en.wikipedia.org/wiki/Public_recursive_name_server)

Providers:
- (unfiltered) AdGuard
- Cloudflare
- Google
- Neustar
- OpenNIC

### CODE REVIEW

**Comment by pvizeli** [comment]
IPv6 is not working currently with docker on the internal network

**Comment by RubenKelevra** [comment]
@pvizeli Ah allright, but this shouldn't be an issue, as dnsmasq just skips the non-working servers.

**Comment by pvizeli** [comment]
right, but why we should include some things which is not working?

**Review by ludeeus — COMMENTED** [review]
I do not think we should merge this.
The current defaults are fine for most installations.
For those that want more/other they can add/change that themselves, we should not do that for them.

**Pull request closed without merging**
