### PR TITLE
nginx_proxy: Fixes init config

### LINKED ISSUE #2546: s6-overlay-suexec: fatal: can only run as pid 1
### Describe the issue you are experiencing

s6-overlay-suexec: fatal: can only run as pid 1
After updating to version 3.1.2.
Issue goes away when reverting to version 3.1.1.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

NGINX Home Assistant SSL proxy

### What is the version of the add-on?

3.1.2

### Steps to reproduce the issue

1. Update to 3.1.2
2. Start nginx add-on
3. Check log
...

### Anything in the Supervisor logs that might be useful for us?

```txt
Home Assistant Core 2022.6.7
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.2
```

### Anything in the add-on logs that might be useful for us?

```txt
s6-overlay-suexec: fatal: can only run as pid 1
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by frenck**
Fixes init config

fixes #2546

### CODE REVIEW

**Review by mdegat01 — APPROVED** [review]

**Comment by Delta1977** [comment]
Fixes https://github.com/home-assistant/addons/issues/2546

**Comment by mdegat01** [comment]
Thanks @frenck !

**Comment by Delta1977** [comment]
Next error ? 

Parse error: Expected string key before ':' at line 1, column 4
[22:19:35] ERROR: Unknown HTTP error occured
parse error: Expected string key before ':' at line 1, column 4
[22:19:35] ERROR: Unknown HTTP error occured
[22:19:35] INFO: Running nginx...
nginx: [emerg] invalid port in upstream "homeassistant.local.hass.io:" in /etc/nginx.conf:62

**Comment by frenck** [comment]
@Delta1977 Please use issues instead of comments on handled PRs. Thanks 👍

**Pull request merged**
