### PR TITLE
Updates deconz to the latest stable version: 2.25.3

### PR DESCRIPTION
**Pull request by francescopeloi**
Updates deconz to the latest stable version: [2.25.3](https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/v2.25.3)

Note: this hasn't been tested locally by me. I am trying to help with what I can, so at least do the code change.

- Phoscon/deconz says that 2.24.3 includes a fix for this deconz addon to work ([source](https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/v2.24.3))
- Problems that were experienced before are discussed in deconz forum ([source](https://forum.phoscon.de/t/phoscon-de-pwa-login-html-does-not-work-anymore/3967)) and on the previous PR ([source](https://github.com/home-assistant/addons/pull/3323))
- I think the [other PR](https://github.com/home-assistant/addons/pull/3323) can be closed, as it's upgrading to a broken version.

### CODE REVIEW

**Comment by francescopeloi** [comment]
I made it a draft to make it clearer that this needs to be locally tested first.

**Comment by manup** [comment]
Hi if it is any help I did test the v2.24.3 version with my external add-on repository: https://github.com/manup/ha_addons_test which was also used to fix the issues mentioned in the changelog.

**Comment by francescopeloi** [comment]
thanks @manup , I put it out of draft state then

**Comment by frenck** [comment]
Assigned myself to run a suite of tests.

**Comment by francescopeloi** [comment]
@frenck , to avoid the risk of wasting your time, it might be worth for [this thread](https://forum.phoscon.de/t/current-deconz-2-24-3-2-25-1-slow-in-response-after-time) to get resolved before you start your testing.

In a nutshell:
- 1 user is experiencing slow network and high cpu usage with deconz v2.24.2 and v2.25.1 (and not with 2.23.2)
- 1 user is experiencing the same with deconz v2.24.3 (and not with 2.23.2)
- it seems that the problem these users are experiencing is with versions > 2.23.2
- one user says it's all good with him
- deconz people have been tagged and hopefully will respond

@manup maybe you can help here, Mimiix tagged @de_employees a couple of times on the thread

Just a suggestion of course, up to you.

**Comment by dutch-erik** [comment]
Latest stable deconz release [v2.25.3](https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/v2.25.3)

**Comment by francescopeloi** [comment]
As @dutch-erik says, there's a new  deconz version which fixes the problems I've highlighted in my previous comment.

@frenck when you get the time this is now ready to be tested, thanks for your help with this.

Putting the PR out of draft.

**Comment by frenck** [comment]
I am picking this up right now. Sorry for the delays, it has been hectic :)

**Review by frenck — APPROVED** [review]
Completed testing on `amd64` & `aarch64` architectures.

Confirmed the add-on worked well. Ingress seems to have no issues or errors, and no oddities in the startup and other logs seen.

Nice! ❤️ 

../Frenck

**Comment by DanielHabenicht** [comment]
Installed and works like a charm with the new IKEA sensors. Thanks for your effort!

**Comment by lasry1** [comment]
I upload the backup for Deconz from the previous Conbee II to the III and it seems it looses the connection of 80% of the ones connected previously

**Comment by MasterEvarior** [comment]
It works beautifully, thanks!

**Comment by rexbron** [comment]
Hi,

I am having an issue with 6.23.0 where it fails to start with an Exec format error:
https://github.com/home-assistant/addons/issues/3470

**Pull request merged**
