### PR TITLE
Update certbot

### LINKED ISSUE #3268: Letsencrypt with ovh dns : certbot-dns-ovh failed with Error adding TXT record: Expecting value: line 1 column 1 (char 0)
### Describe the issue you are experiencing

can not renew an ovh certificate.

this is an issue from certbot, https://github.com/certbot/certbot/issues/9799
due to Lexicon

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Almond

### What is the version of the add-on?

4.12.9

### Steps to reproduce the issue

1. have a ovh dns certificate to renew
2. start the add-on
3. log contains error:

> [07:40:31] INFO: Selected DNS Provider: dns-ovh
[07:40:31] INFO: Use propagation seconds: 60
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Renewing an existing certificate for xxxxxxxxxxx
**Error adding TXT record: Expecting value: line 1 column 1 (char 0)**
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.

## System Information

version | core-2023.10.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.5
os_name | Linux
os_version | 6.1.45
arch | x86_64
timezone | Europe/Paris
config_dir | /config

### Anything in the Supervisor logs that might be useful for us?

_No response_

### Anything in the add-on logs that might be useful for us?

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Fabien-B**
I updated all python packages to their latest version, except cryptography, whose latest version requires Rust 1.56, but the package manager ships Rust 1.52.1.
I tried installing rust via another method but I couldn't get it to work on all platforms.

This PR fixes #3268

### CODE REVIEW

**Comment by ericsche** [comment]
@agners can you help, we are few people impacted by the ovh dns bug thats been fixes the latest update that PR would fix.
thanks for the help

**Comment by ericsche** [comment]
adding the issue in question https://github.com/home-assistant/addons/issues/3268

**Comment by Tetef92** [comment]
I need help 😊 : I'm waiting for the fix : 
- When the Let's Encrypt 4.13.0 will be available ?
- Will it fix the OVH "Error adding TXT record" Issue ?

**Comment by adri123** [comment]
Please make this fix append, thank you to the team !

**Comment by ericsche** [comment]
> I need help 😊 : I'm waiting for the fix :
> 
> * When the Let's Encrypt add-on 4.13.0 will be available ?
> * Will it fix the OVH "Error adding TXT record" Issue ?

yes the PR proposed by @Fabien-B will fix the issue. We need one of the maintainers of the add-on to valid this update to fix the issue for us.

**Comment by ericsche** [comment]
@frenck could you please review this PR we are a few users t
where our certificate is expired and we can connect to our HA because of this bug. Fabian propose to update the certbot and its dependencies to fix the issue.

**Comment by Fabien-B** [comment]
If you REALLY need it, I forked the addon repository at this address : https://github.com/Fabien-B/HA_addons
I ran the github action, and it build the _i386_, _amd64_ and _aarch64_ versions of this addon. It failed for _armhf_ and _armv7_, I don't exactly know why.
I tested it on my raspberry pi 4, it works.
There is still a warning, but it manage to renew the certificate.
However please note that I won't be maintaining this repository.

**Comment by agners** [comment]
It seems that the OVA problem resolved itself is this correct? So this isn't as urgent anymore, probably still worthwhile.

**Comment by InhouseMedia** [comment]
Hi, Yes i need this change because the Direct Admin DNS  was not working and is fixed with updating the package:
https://github.com/cybercinch/certbot-dns-directadmin/releases

Maybe rollback the CRYPTOGRAPHY_VERSION only will fix this build issue.

**Comment by agners** [comment]
Ok, since the problem this initially tried to resolve is resolved without this, and armhf build is not passing, let's close this.

**Pull request closed without merging**
